### ISSUE TITLE
The edit catalog modal remains open when changing maps

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9016] opened 2023-03-15 09:19 UTC
## Description

The edit catalog modal remains open when changing maps

## How to reproduce

-  Follow the steps in the video below:

https://user-images.githubusercontent.com/56537133/225263177-7545adce-dff2-4a44-807e-5b52439b80f8.mov

## Other useful information
It is also present on master

**Comment by dsuren1** [comment] 2023-03-15 13:59
**Investigation**:
This is caused by catalog `mode` not being reset when navigating to home page. Currently the mode is reset when closing the panel.

Fix is to reset catalog **mode** `onChangeCatalogMode("view")`  when the `CatalogServiceEditor` component is unmounted.

**Comment by tdipisa** [comment] 2023-03-15 14:40
Can it be a regression introduced recently @dsuren1 ?

**Comment by dsuren1** [comment] 2023-03-16 07:23
It's not a regression as it also exists in previous versions (ex: tested on v2022.02.02, v2022.02.00)

**Closed** 2023-03-16 13:53 UTC
Labels: bug
