### ISSUE TITLE
Webpack-cli error occurs on "npm start"

### ISSUE THREAD

**Issue by dhlambert** [geosolutions-it/MapStore2#6511] opened 2021-02-05 01:42 UTC
## Description
Unable to run mapstore2 for development due to an error occurring after `npm start`. Occurs on release `v2021.01.00` and `master`. 

## How to reproduce

1. Checkout either `master` or tag `v2021.01.00`
2. Follow README instructions for `Start developing your custom app`.
3. The issue occurs after installation when running `npm start`.

*Expected Result*
Mapstore builds and runs successfully for local development.

*Current Result*
```
user@user-lp:~/GIS/MapStore/mapstore2-upstream$ npm start

> mapstore2@0.2.0 start /home/user/GIS/MapStore/mapstore2-upstream
> webpack serve --progress --color --port 8081 --hot --inline --config build/webpack.config.js --content-base web/client

[webpack-cli] TypeError: cli.isValidationError is not a function
    at Command.<anonymous> (/home/user/GIS/MapStore/mapstore2-upstream/node_modules/@webpack-cli/serve/lib/index.js:96:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/home/user/GIS/MapStore/mapstore2-upstream/node_modules/webpack-cli/lib/webpack-cli.js:708:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mapstore2@0.2.0 start: `webpack serve --progress --color --port 8081 --hot --inline --config build/webpack.config.js --content-base web/client`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mapstore2@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-02-04T22_30_54_787Z-debug.log
```

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
**OS:** Ubuntu 18.04
**npm version:** 6.14.5
**node version:** 14.4.0
**mvn version:** 3.6.3

This issue has also occurred on another separate machine as well.

**Comment by MV88** [comment] 2021-02-09 14:48
apparently updating webpack-cli to 4.5.0 fixes it, 
is caused by https://github.com/webpack/webpack-cli/issues/2422

If like, you can provide a pr that will very appreciated :)

**Comment by MV88** [comment] 2021-02-09 15:49
we have included the update of the lib in [this](https://github.com/geosolutions-it/MapStore2/pull/6288) other pr, so no need to od anything here

**Comment by MV88** [comment] 2021-02-10 09:33
we have merged that PR, so i'm going to close this one.

thanks for taking time to open this issue

if you need more support you can use the mailing lists for [devs](https://groups.google.com/group/mapstore-developers) or [users](https://groups.google.com/group/mapstore-users)

**Closed by MV88** 2021-02-10 09:33 UTC
Labels: bug

**Comment by dhlambert** [comment] 2021-02-10 19:35
Thanks for the help with this @MV88 :)
