### ISSUE TITLE
Permission editor available for unauthorized users

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4593] opened 2019-12-03 14:12 UTC
### Description
The permission editor in a resource should be available only for the owner of that resource (the one who created it) and the administrator 
Actually the permission editor is available also for normal users with editing permission and this thing needs to be fixed. In particular the permission editor should be removed from the following situations:

### FOR MAPS, DASHBOARDS AND STORIES

* Login as admin
* Create a new map/dash/story
* Save it assigning the following permission: `Testers` - `can edit`
* Go back to the homepage
* Logout from admin and login as a tester
* Open the map/dash/story just created
* Click on Burger menu
* Click on save

**Problem:** The permission editor should not be present

### FOR DASHBOARDS AND STORIES

* Login as admin
* Create a new dash/story
* Save it assigning the following permission: `Testers` - `can edit`
* Go back to the homepage
* Logout from admin and login as a tester
* In homepage, click on edit properties on the dash/story just created

**Problem:** The permission editor should not be present

### Other useful information (optional):
The only situation where we have the ideal situation is the following:
* Login as admin
* Create a new map
* Save it assigning the following permission: `Testers` - `can edit`
* Go back to the homepage
* Logout from admin and login as a tester
* In homepage, click on edit properties on the map just created
* The permission editor is not present

**Comment by ElenaGallo** [comment] 2019-12-09 09:53
- [ ] now for the **first situation** the permission is forbidden but the permission editor is still present 

FOR MAPS, DASHBOARDS AND STORIES

- Login as admin
- Create a new map/dash/story
- Save it assigning the following permission: Testers - can edit
- Go back to the homepage
- Logout from admin and login as a tester
- Open the map/dash/story just created
- Click on Burger menu
- Click on save

*Current Result*: The permission editor is Forbidden but the options to change the permission are present on the Eidt properties window
![45](https://user-images.githubusercontent.com/56537133/70425597-cc557280-1a71-11ea-8723-4c4d8dd399f7.JPG)

*Expected Result*: The permission editor should not be present

- [ ] the **second situacion** has not been fixed 

FOR DASHBOARDS AND STORIES
- Login as admin
- Create a new dash/story
- Save it assigning the following permission: Testers - can edit
- Go back to the homepage
- Logout from admin and login as a tester
- In homepage, click on edit properties on the dash/story just created

*Current Result*: The permission editor is availabe 
*Expected Result*: The permission editor should not be present

**Comment by tdipisa** [comment] 2019-12-09 16:47
@offtherailz please check this to see if we can close the issue quickly in this milestone.

**Comment by offtherailz** [comment] 2019-12-10 12:28
Here my report @tdipisa : 

The last problem notified by @ElenaGallo is caused by a different bug. 

It is not a problem to show or not show permission, but a problems in sequence, when try to remove your own permission while saving.

In fact, she's trying to remove edit permission to testers user while she logged in as tester. The bug tries to update the permission before update the resource itself,  causing the Forbidden error. 

during my tests and trying to restore the normal visualization of permission tools, i noticed **Another bug is about geostore policy and owner:** 

Geostore seems to have different behaviors if you specify or not the owner (some resources seems to display the owner, other don't). 

 - If owner is present, mapstore don't allow to edit permission to user with write permissions (but anyway you can edit and delete contents)

 - If owner is not present you can edit permission as well as edit or delete the resource itself

Here 2 resources with exactly the same permissions, created by the same user (offtherailz_tester) 
- 16589 permissions are accessible by testers user members
- 16666 is not accessible by other testers user members.

Here the responses from the server, as admin, for security rules and resources (for owner)
```
16589: {"SecurityRuleList":{"SecurityRule":[{"canRead":true,"canWrite":true,"group":{"groupName":"testers","id":10933}},{"canRead":true,"canWrite":true,"user":
{"id":12417,"name":"offtherailz_tester"}}]}}
16666: {"SecurityRuleList":{"SecurityRule":[{"canRead":true,"canWrite":true,"group":{"groupName":"testers","id":10933}},{"canRead":true,"canWrite":true,"user":{"id":12417,"name":"offtherailz_tester"}}]}} 

Result From http://localhost:8081/rest/geostore/extjs/search/category/MAP/*tester*/thumbnail,details,featured?start=0&limit=12 (by admin)
{"success":true,"totalCount":2,"results":[
    {"canDelete":true,"canEdit":true,"canCopy":true,"creation":"2019-12-10 12:28:13.769","lastUpdate":"2019-12-10 12:29:07.236","description":"editable for testers","id":16666,"name":"offtherailz_tester map ","owner":"offtherailz_tester"}, <-- with owner can edit permission
    {"canDelete":true,"canEdit":true,"canCopy":true,"creation":"2019-12-10 11:10:40.68","lastUpdate":"2019-12-10 11:11:20.529","description":"test map with edit permission for testers group","id":16568,"name":"editable for testers","owner":"admin"}]} <-- another resource, with admin owner, cannot edit permission

Result From http://localhost:8081/rest/geostore/extjs/search/category/GEOSTORY/*tester*/thumbnail,details,featured?start=0&limit=12 (by admin)
{"success":true,"totalCount":1,"results":{"canDelete":true,"canEdit":true,"canCopy":true,"creation":"2019-12-10 11:32:35.516","lastUpdate":"2019-12-10 11:52:07.98","description":"","id":16589,"name":"story of offtherailz_tester"}} <-- No owner, can edit permissions
```


## Proposed solution

**About the first bug:** 
I'm going to check how much it takes. Anyway, it's a corner case. 

**About the second bug:** 
Good solution is to remove this strange owner check for permission only (I think it's a bug of geostore) 
In the meanwhile I propose to check and display permission **always**.We will have a failure sometimes, because of this inconsinstancy in mapstore, but the bug is inside GeoStore. We can hide this bug by denying permission edit when owner is present, but this makes the UI a little unconstinstent.

**Comment by offtherailz** [comment] 2019-12-10 16:25
# Solution Implemented
- Hide permission editor if owner is present, and is not the current user (only maps have owner, so only for maps)
- show permission editor in any other case (Save modal is visibile only to the user with write permission). 

this solves the 2 bugs above 
- first is not present anymore, because permission editing now is denied also for not owners, in case of maps.
 - second permissions are hidden when not allowed.

I'm going to open an issue on GeoStore about the problem of the owner.

**Comment by tdipisa** [comment] 2019-12-10 16:41
>I'm going to open an issue about the problem of the owner.
@offtherailz I would like to open also a new issue in MS for this to refer to the GeoStore one.

**Comment by offtherailz** [comment] 2019-12-10 17:08
I reported everything in MapStore, for the moment, this issue: https://github.com/geosolutions-it/MapStore2/issues/4634

**Closed** 2019-12-11 11:15 UTC
Labels: Accepted, Priority: High
