### ISSUE TITLE
Layer added to a context don't use mapInfoConfiguration

### ISSUE THREAD

**Issue by jusabatier** [geosolutions-it/MapStore2#8695] opened 2022-10-14 07:57 UTC
## Description
The layers added after open a context, via catalog or URL parameters doesn't use mapInfoConfiguration/infoFormat defined in configuration.

Those layers use the TEXT format, instead of using the default one defined in context's mapInfoConfiguration/infoFormat.

In our case we want them to use HTML, so we set : 

```
"mapInfoConfiguration":{
    "showEmptyMessageGFI":false,
    "infoFormat":"text/html"
}
```

in our context's json.

## How to reproduce
=> quick example : https://geoportail.lepuyenvelay.fr/mapstore/#/context/Test?addLayers=website:points_de_vente_libelle;gpvgs&mapInfo=website:points_de_vente_libelle&mapInfoFilter=%22id=15%22
=> Other method (manually)
- Open a context with above configuration in it JSON
- Add a layer via the TOC
- Try to click on a feature

*Expected Result*
Use the HTML format to display GFI

*Current Result*
It use the TEXT one

- [x] Not browser related

**Comment by tdipisa** [comment] 2022-10-17 12:43
Hi @jusabatier 

the _mapInfoConfiguration_ is not yet supported for app contexts. I know you have also sent an email in the ML and I can confirm what @offtherailz said. 

As far as these kind of Identify settings are concerned, we are keeping track of the related enhancement through #5504.

Thank you for opening this issue. I'm going to connect it to the main one to schedule it as soon as possible as part of a new release.

**Comment by tdipisa** [comment] 2022-10-18 15:18
@jusabatier I'm sorry but it seems yesterday I've not properly understood your issue for some reason. We can effectively provide a quick fix for this since you have identified a small regression. My comment above is referencing another improvement.

**Closed** 2022-10-18 15:57 UTC
Labels: bug, Priority: High, Accepted, C169-Rennes-Métropole-2021-GeOrchestra3

**Comment by jusabatier** [comment] 2022-11-29 08:30
Hi, this issue is closed but it still not work.

Can you reopen and try to fix it please @ElenaGallo @tdipisa ?

**Comment by jusabatier** [comment] 2022-11-29 08:57
I just tried with this war : https://github.com/georchestra/mapstore2-georchestra/actions/runs/3459472959

And it appear to work.

Do you know when you will publish the final release for Group 3 ?
