### ISSUE TITLE
Issue running npm run backend on some environments

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7473] opened 2021-10-26 09:20 UTC
## Description
@allyoucanmap and @DavidQuartz notified some issues running the new `npm run backend` on their environments.  Initially it has been developed using Windows and it works on @offtherailz 's environment (Linux Ubuntu). 

- @allyoucanmap dev env is on Windows
- @DavidQuartz dev env is on MacOS

## How to reproduce
-  run `npm run backend` or as for doc `cd product; mvn cargo:run;` (after a first `mvn clean install`)

*Expected Result*
- Backend starts at port 8080

*Current Result*
Some errors occurs

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
- [x]On windows: <-- This seems to be solved and caused only by a local problem

```
[INFO] MapStore 2 - Backend Services ...................... SUCCESS [  8.558 s]
[INFO] MapStore 2 - WAR ................................... SUCCESS [01:27 min]
[INFO] MapStore 2 ......................................... SUCCESS [  0.038 s]
[INFO] MapStore Product Web Application ................... SUCCESS [03:19 min]
[INFO] MapStore Root ...................................... SUCCESS [  0.046 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:56 min
[INFO] Finished at: 2021-10-26T09:42:20+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for it.geosolutions.mapstore:mapstore-product:war:1.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.cargo:cargo-maven3-plugin is missing. @ line 275, column 17
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] -------------< it.geosolutions.mapstore:mapstore-product >--------------
[INFO] Building MapStore Product Web Application 1.3-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- cargo-maven3-plugin:1.9.8:run (default-cli) @ mapstore-product ---
[INFO] [en3.ContainerRunMojo] Resolved container artifact org.codehaus.cargo:cargo-core-container-tomcat:jar:1.9.8 for container tomcat8x
[INFO] [talledLocalContainer] Tomcat 8.x starting...
[INFO] [stalledLocalDeployer] Deploying [/mnt/c/Users/geosolutions/workspace/MapStore2/./product/target/mapstore.war] to [/mnt/c/Users/geosolutions/workspace/MapStore2/./product/target/apache-tomcat-8.5.69/webapps]...
[INFO] [talledLocalContainer] Oct 26, 2021 9:43:26 AM org.apache.catalina.startup.SetAllPropertiesRule begin
[WARNING] [talledLocalContainer] WARNING: [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'emptySessionPath' to 'cargo.tomcat.connector.emptySessionPath' did not find a matching property.
[INFO] [talledLocalContainer] Oct 26, 2021 9:43:26 AM org.apache.coyote.AbstractProtocol init
[INFO] [talledLocalContainer] INFO: Initializing ProtocolHandler ["http-nio-8080"]
[INFO] [talledLocalContainer] Oct 26, 2021 9:43:26 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
[INFO] [talledLocalContainer] INFO: Using a shared selector for servlet write/read
[INFO] [talledLocalContainer] Oct 26, 2021 9:43:26 AM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deploying web application archive [/mnt/c/Users/geosolutions/workspace/MapStore2/product/target/apache-tomcat-8.5.69/webapps/cargocpc.war]
[INFO] [talledLocalContainer] Oct 26, 2021 9:43:27 AM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deployment of web application archive [/mnt/c/Users/geosolutions/workspace/MapStore2/product/target/apache-tomcat-8.5.69/webapps/cargocpc.war] has finished in [840] ms
[INFO] [talledLocalContainer] Oct 26, 2021 9:43:27 AM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deploying web application archive [/mnt/c/Users/geosolutions/workspace/MapStore2/product/target/apache-tomcat-8.5.69/webapps/mapstore.war]
[INFO] [talledLocalContainer] Oct 26, 2021 9:44:47 AM org.apache.jasper.servlet.TldScanner scanJars
[INFO] [talledLocalContainer] INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[INFO] [yer.DeployerWatchdog] Deployable [http://localhost:8080/cargocpc/index.html] failed to finish deploying within the timeout period [120000]. The Deployable state is thus unknown.
[WARNING] [talledLocalContainer] org.codehaus.cargo.container.ContainerException: Deployable [http://localhost:8080/cargocpc/index.html] failed to finish deploying within the timeout period [120000]. The Deployable state is thus unknown.
[ERROR] Starting container [org.codehaus.cargo.container.tomcat.Tomcat8xInstalledLocalContainer@17814b1c] failed
org.codehaus.cargo.container.ContainerException: Deployable [http://localhost:8080/cargocpc/index.html] failed to finish deploying within the timeout period [120000]. The Deployable state is thus unknown.
    at org.codehaus.cargo.container.spi.deployer.DeployerWatchdog.watch (DeployerWatchdog.java:111)
    at org.codehaus.cargo.container.spi.AbstractLocalContainer.waitForCompletion (AbstractLocalContainer.java:387)
    at org.codehaus.cargo.container.spi.AbstractLocalContainer.start (AbstractLocalContainer.java:234)
    at org.codehaus.cargo.maven3.ContainerStartMojo.executeLocalContainerAction (ContainerStartMojo.java:83)
    at org.codehaus.cargo.maven3.ContainerRunMojo.doExecute (ContainerRunMojo.java:95)
    at org.codehaus.cargo.maven3.AbstractCargoMojo.execute (AbstractCargoMojo.java:439)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Press Ctrl-C to stop the container...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:03 min
[INFO] Finished at: 2021-10-26T09:45:26+02:00
[INFO] ------------------------------------------------------------------------
```

- [ ] On MacOS, please @DavidQuartz comment:

```[INFO] [talledLocalContainer] Hibernate: select category0_.id as id1_1_, category0_.name as name2_1_ from public.gs_category category0_ order by category0_.name asc
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.core.StandardContext listenerStart
[INFO] [talledLocalContainer] SEVERE: Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
[INFO] [talledLocalContainer] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geostoreInitializer' defined in URL [file:/Users/david/Documents/Geosolutions/MapStore2/product/target/apache-tomcat-8.5.69/webapps/mapstore/WEB-INF/classes/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Error while initting categories.
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
[INFO] [talledLocalContainer] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
[INFO] [talledLocalContainer] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
[INFO] [talledLocalContainer] at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
[INFO] [talledLocalContainer] at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
[INFO] [talledLocalContainer] at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
[INFO] [talledLocalContainer] at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4763)
[INFO] [talledLocalContainer] at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5232)
[INFO] [talledLocalContainer] at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
[INFO] [talledLocalContainer] at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
[INFO] [talledLocalContainer] at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
[INFO] [talledLocalContainer] at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
[INFO] [talledLocalContainer] at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
[INFO] [talledLocalContainer] at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
[INFO] [talledLocalContainer] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] [talledLocalContainer] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [talledLocalContainer] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] [talledLocalContainer] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] [talledLocalContainer] at java.lang.Thread.run(Thread.java:748)
[INFO] [talledLocalContainer] Caused by: java.lang.RuntimeException: Error while initting categories.
[INFO] [talledLocalContainer] at it.geosolutions.geostore.init.GeoStoreInit.initCategories(GeoStoreInit.java:202)
[INFO] [talledLocalContainer] at it.geosolutions.geostore.init.GeoStoreInit.afterPropertiesSet(GeoStoreInit.java:89)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
[INFO] [talledLocalContainer] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
[INFO] [talledLocalContainer] ... 25 more
[INFO] [talledLocalContainer]
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.core.StandardContext startInternal
[INFO] [talledLocalContainer] SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.core.StandardContext startInternal
[INFO] [talledLocalContainer] SEVERE: Context [/mapstore] startup failed due to previous errors
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
[WARNING] [talledLocalContainer] WARNING: The web application [mapstore] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
[WARNING] [talledLocalContainer] WARNING: The web application [mapstore] appears to have started a thread named [H2 File Lock Watchdog /Users/david/Documents/Geosolutions/MapStore2/product/target/apache-tomcat-8.5.69/webapps/mapstore/geostore.lock.db] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
[INFO] [talledLocalContainer] java.lang.Thread.sleep(Native Method)
[INFO] [talledLocalContainer] org.h2.store.FileLock.run(FileLock.java:506)
[INFO] [talledLocalContainer] java.lang.Thread.run(Thread.java:748)
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
[WARNING] [talledLocalContainer] WARNING: The web application [mapstore] appears to have started a thread named [H2 Log Writer GEOSTORE] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
[INFO] [talledLocalContainer] java.lang.Object.wait(Native Method)
[INFO] [talledLocalContainer] org.h2.store.WriterThread.run(WriterThread.java:103)
[INFO] [talledLocalContainer] java.lang.Thread.run(Thread.java:748)
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deployment of web application archive [/Users/david/Documents/Geosolutions/MapStore2/product/target/apache-tomcat-8.5.69/webapps/mapstore.war] has finished in [10,611] ms
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.startup.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deploying web application directory [/Users/david/Documents/Geosolutions/MapStore2/product/target/apache-tomcat-8.5.69/webapps/manager]
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.startup.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deployment of web application directory [/Users/david/Documents/Geosolutions/MapStore2/product/target/apache-tomcat-8.5.69/webapps/manager] has finished in [33] ms
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.startup.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deploying web application directory [/Users/david/Documents/Geosolutions/MapStore2/product/target/apache-tomcat-8.5.69/webapps/host-manager]
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.catalina.startup.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deployment of web application directory [/Users/david/Documents/Geosolutions/MapStore2/product/target/apache-tomcat-8.5.69/webapps/host-manager] has finished in [14] ms
[INFO] [talledLocalContainer] Oct 26, 2021 1:46:52 PM org.apache.coyote.AbstractProtocol start
[INFO] [talledLocalContainer] INFO: Starting ProtocolHandler ["http-nio-8080"]
[INFO] [talledLocalContainer] Tomcat 8.x started on port [8080]
[INFO] Press Ctrl-C to stop the container...
```

The second bug has been found also on GeoFIT installation

## Other useful information

Connected to https://github.com/geosolutions-it/DevOps/issues/1025

**Comment by mbarto** [comment] 2021-11-04 14:18
@tdipisa after some investigation, we have found that:
 * @allyoucanmap issues were mostly caused by a slow environment, where tomcat took too much time to start (more than 2 minutes), this can be eventually solved by raising the default timeout to something like 5 minutes
 * @DavidQuartz issue was not solved, but the error suggests something weird in his environment, apparently a very old version of a library (xercesImpl) is for some reason in java classpath, so it is used instead of the one included with MapStore. We tried removing xercesImpl from MapStore (the library is not needed anymore by java >=8 but included by some nested dependency), but the old version was still used, and we couldn't find where it is (we would need a MacOS expert here); we also found maven reporting java17 when java8 / 11 was manually installed instead

@DavidQuartz should be able to work using the docker container: we should evaluate if we want to push this way of developing instead of running the backend via npm / maven

Possible actions:
 * increase tomcat starting timeout (trivial)
 * remove xercesImpl dependency (trivial, but not mandatory)
 * investigate on java17 compatibility
 * push for using docker in the docs

**Comment by taba90** [comment] 2022-07-25 09:55
xerces is a transitive dependency of xom.
Xom seems to not be actually needed by geostore. I've open pr https://github.com/geosolutions-it/geostore/pull/299

**Comment by tdipisa** [comment] 2022-07-25 15:11
@offtherailz the PR has been merged. As we agreed in the status call today, please check the update in DEV and let us know if the issue can be closed.

**Comment by offtherailz** [comment] 2022-07-25 15:17
Here we need to test the latest docker instance to see the problem is solved. Let's wait for a recent build (tomorrow) @randomorder .

**Comment by tdipisa** [comment] 2022-07-25 15:24
@offtherailz 

>Here we need to test the latest docker instance to see the problem is solved

Do you mean a test in Ms DEV?

**Comment by offtherailz** [comment] 2022-07-25 16:38
I mean on the environment that produced the original problem (https://github.com/geosolutions-it/DevOps/issues/1025)

**Closed** 2022-08-02 10:35 UTC
Labels: bug, investigation, Accepted, C211-GEOFIT-2022-OPENID
