### ISSUE TITLE
Annotations UI issues

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9447] opened 2023-09-14 13:41 UTC
# Description

Issue to collect bugs found during tests of the new annotation tool.

## Other useful information

From https://github.com/geosolutions-it/MapStore2/issues/9396#issuecomment-1717948989

```[tasklist]
### Tasks
- [ ] #9650
- [ ] #9651
- [ ] #9653
- [ ] #9654
```

**Comment by tdipisa** [comment] 2023-10-24 09:50
> 5- On the point style tab, it is possible to overlay multiple icons and markers

This is not a bug @ElenaGallo. Having the possibility to add multiple rules is is now possible to configure more complex styles.

**Comment by offtherailz** [comment] 2024-05-08 07:35
Closing because moved in done

**Closed by offtherailz** 2024-05-08 07:35 UTC
Labels: bug, Accepted, annotations, 3D, C027-COMUNE_FI-2023-SUPPORT
