### ISSUE TITLE
Time Range UI issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6833] opened 2021-05-06 09:36 UTC
## Description

It seems, in certain cases, there is a UI issue representing the to extremes of the time range.

## How to reproduce

- Open [this](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/33986) map
- Open the time slider

*Expected Result*

It should be represented as reported below
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/54c53161-ae28-4768-947a-26ba1981e1f7)

*Current Result*

![2021_05_06_11_31_25_MapStore_HomePage.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/a5304344-df6d-4030-9acf-7da7c00dca6e)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

In [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10279) the range extremes is represented correctly instead.

**Comment by MV88** [comment] 2021-06-01 15:38
@tdipisa the UI seems consistent with the data currently configured
it goes from june 2021 o april 2021
![image](https://user-images.githubusercontent.com/11991428/120351379-200be980-c300-11eb-8769-c0d48e916475.png)
are they maybe missconfigured?

**Comment by tdipisa** [comment] 2021-06-01 15:58
@MV88 look better at images attached in the issue description.

**Comment by MV88** [comment] 2021-06-01 16:11
@QSafariallahkheili 
- Can you check if the values are saved within the map wrongly or if they come from the server like in my last picture??
- Alsocan you add a validation check that the starting time is not greater than the ending time?

**Comment by QSafariallahkheili** [comment] 2021-06-09 13:25
> @QSafariallahkheili
> 
> * Can you check if the values are saved within the map wrongly or if they come from the server like in my last picture??

The map was contained inverted dates, so we inverted them and then we have saved the map.


> * Also can you add a validation check that the starting time is not greater than the ending time?

There is already validation in place, and I cannot create invalid ranges

**Comment by MV88** [comment] 2021-06-09 13:26
ok thanks, going to close this

**Comment by tdipisa** [comment] 2021-06-09 14:24
> The map was contained inverted dates, so we inverted them and then we have saved the map.

If I remember correctly from my test @QSafariallahkheili, these were time values set by MS and not by a mistake of the user (eg. when adding the layer in map from the catalog tool and them opening the timeline tool enabling also the time range button).

Did you try this use case?

**Comment by QSafariallahkheili** [comment] 2021-06-09 15:57
> > The map was contained inverted dates, so we inverted them and then we have saved the map.
> 
> If I remember correctly from my test @QSafariallahkheili, these were time values set by MS and not by a mistake of the user (eg. when adding the layer in map from the catalog tool and them opening the timeline tool enabling also the time range button).
> 
> Did you try this use case?

I add different layers ("METOP B ORBITAL TRACK", "METOP C ORBITAL TRACK", "S3A Orbital Tracks" and "S3B Orbital Tracks") from Eum service. As shown on the following screenshot, all the mentioned layers have time information and the behaviour of timeline GUI is as expected. 


<img width="1279" alt="Screenshot 2021-06-09 at 17 41 14" src="https://user-images.githubusercontent.com/50631096/121388106-79e96080-c94b-11eb-922c-9da49daebffb.png">

**Comment by tdipisa** [comment] 2021-06-09 16:00
ok @QSafariallahkheili, thank you. @MV88 in this case the issue should be moved in test colum so that @ElenaGallo can check it before closing the issue.

**Comment by tdipisa** [comment] 2021-06-17 11:31
@MV88 @QSafariallahkheili @ElenaGallo It seems that my suspects were correct here. It does not seem to me that the problem can be closed.

![timeline](https://user-images.githubusercontent.com/1280027/122388473-35278000-cf70-11eb-8fa8-1106c99c2ad6.gif)

**Comment by MV88** [comment] 2021-06-17 11:45
@tdipisa 
**now** it is more clear how to reproduce the issue

@QSafariallahkheili can you check?

- open **the new map**
- add from wms the meteorite layer
- use a time range in the timeline
- save the map
- (re)load the map

**expected**
date range is the same 

**current**
date range is wrong

**Comment by MV88** [comment] 2021-06-17 12:19
@tdipisa yes, i just have written them to make them quickly accessible

**Comment by MV88** [comment] 2021-06-18 13:44
@tdipisa we have spotted the source of problems and was due to asyncronicity
@QSafariallahkheili will provide shortly a fix for this

**Closed** 2021-06-22 08:17 UTC
Labels: Accepted, Good first issue, Internal, Priority: High, bug
