### ISSUE TITLE
Geostory creation and context seems broken for new projects?

### ISSUE THREAD

**Issue by shermp** [geosolutions-it/MapStore2#5613] opened 2020-07-09 04:51 UTC
## Description
I'm attempting to test out MapStore2 to see if it will work for us, however I'm running into an issue when attempting the run a test war built from a project.

When attempting to create a new storymap (logged in as admin), I get the following message:
`geostory.errors.loading.notFound
This story does not exist`

Also, when attempting to create a new context (from Manage Contexts), I get the following:
`Error loading context
There was an error loading the map or the context. Please contact the administrator`

This might be separate, or part of the issue, but Chrome shows some of the following issues:
```
main-maps.js?74695eca1d904be65b1b:7 GET http://localhost:8082/main-maps/configs/newgeostory.json 404 (Not Found)
main-maps.js?74695eca1d904be65b1b:78 Uncaught TypeError: Cannot read property 'type' of undefined
    at main-maps.js?74695eca1d904be65b1b:78
    at main-maps.js?74695eca1d904be65b1b:283
    at main-maps.js?74695eca1d904be65b1b:283
    at main-maps.js?74695eca1d904be65b1b:283
    at main-maps.js?74695eca1d904be65b1b:283
    at main-maps.js?74695eca1d904be65b1b:283
    at t.handleClick (main-maps.js?74695eca1d904be65b1b:156)
    at t.handleClick (main-maps.js?74695eca1d904be65b1b:156)
    at Object.m (main-maps.js?74695eca1d904be65b1b:218)
    at w (main-maps.js?74695eca1d904be65b1b:218)
    at main-maps.js?74695eca1d904be65b1b:218
    at E (main-maps.js?74695eca1d904be65b1b:218)
    at M (main-maps.js?74695eca1d904be65b1b:218)
    at C (main-maps.js?74695eca1d904be65b1b:218)
    at P (main-maps.js?74695eca1d904be65b1b:218)
    at gn (main-maps.js?74695eca1d904be65b1b:218)

main-maps.js?74695eca1d904be65b1b:7 GET http://localhost:8082/main-maps/pluginsConfig.json 404 (Not Found)
```

## How to reproduce

-  Clone the MapStore2 repository
-  `git checkout v2020.02.00`
- `node ./createProject.js standard main-maps 0.1.0 "Test map for name" none  ../mainmap`
- `cd ../mainmap`
- `git add .`
- `git commit -m "Commit message"
- `chmod +x ./build.sh`
- `./build.sh 0.0.1`
- (go make a coffe/tea)
- `cp ./web/target/main-maps.war path/to/mapstore2-2020.02.00-bin/webapps`
- `cd path/to/mapstore2-2020.02.00-bin && ./mapstore2-startup.sh`
- Visit http://localhost:8082/main-maps
- login as admin
- Click new storyboard button

*Expected Result*

The UI for creating a storymap or context should be shown

*Current Result*

Get shown an error with `geostory.errors.loading.notFound
This story does not exist` or `Error loading context
There was an error loading the map or the context. Please contact the administrator`

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This is my first time with MapStore2, so unsure if this is a bug, or me missing some important step.

**Comment by ewsterrenburg** [comment] 2020-08-11 15:01
I can confirm this issue (and also that if `configs/newgeostory.json` is included, it all works nicely).
`extensions.json` seems also missing, yet I guess that doesn't lead to issues.

**Comment by tdipisa** [comment] 2020-08-13 15:47
@ewsterrenburg @shermp, thank you for reporting this. We will check it asap and we will provide a fix in the current stable branch (2020.02.xx) if needed. I will keep you updated.

**Comment by MV88** [comment] 2020-08-14 15:34
Hi all i have opened and merged a pr for fixing the geostory creation problem [here](https://github.com/geosolutions-it/MapStore2/pull/5790) and backported [here](https://github.com/geosolutions-it/MapStore2/pull/5794)

Unfortunately there are some other problems related to the creation of a new standard project that will be addressed in [this](https://github.com/geosolutions-it/MapStore2/issues/new?assignees=&labels=bug&template=bug.md&title=) separate issue

if you don't need to run local tests, i can suggest you to run a second time the npm install, as it seems to be able to complete the installation correctly

**Comment by ewsterrenburg** [comment] 2020-08-14 21:29
@MV88 Thanks! I also noticed the issue with `npm install`, yet since every thing seemed fine after a second attempt I thought it was a local fluke.

**Comment by offtherailz** [comment] 2020-09-03 08:32
`npm run compile doesn't work with projects created 
because of this line:
```
    "compile": "npm run clean && mkdirp ./dist && node --max_old_space_size=2048 webpack --config prod-webpack.config.js --env.production",
```
should be replaced with something like:
```
        "compile": "npm run clean && mkdirp ./dist && node --max_old_space_size=2048 ./node_modules/webpack/bin/webpack.js --config prod-webpack.config.js --env.production",

```

**Closed** 2020-09-07 16:35 UTC
Labels: Accepted, Priority: High, bug
