### ISSUE TITLE
Dashboard - Map Widget - Open/closed group button 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4709] opened 2020-01-13 11:58 UTC
## Description

In dashboard, adding a map widget with at least a layer, the open/closed group button dose not work. 
![dashbutton](https://user-images.githubusercontent.com/56537133/72254310-e8fe4080-3603-11ea-8886-1706afb759c2.gif)

## How to reproduce

-  Open mapstore
- Login as admin
- New dashboard
- Add a widget
- Select MAP as widget type
- Select and use a map with at least a layer
- Click on open/closed group

*Expected Result*

The open/closed group button does not close the group
*Current Result*

The open/closed group button worksand close the group 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by gitcontributor** [comment] 2020-06-04 09:21
Hi @tdipisa. I can't reproduce the bug both on dev and qa.

**Comment by tdipisa** [comment] 2020-06-04 09:30
@gitcontributor, moving it in test. @ElenaGallo can you please test it again?

**Comment by ElenaGallo** [comment] 2020-06-05 12:28
@tdipisa @gitcontributor the bug is still present  (both on dev and qa) when the empty map is used. 

## How to reproduce
-  Open mapstore
- Login as admin
- New dashboard
- Add a widget
- Select MAP as widget type
- Select the Empty map
- Click on +
- Add ETOPO_Shadow map
- Click on +
- Click on open/closed group

**Closed** 2020-06-11 13:53 UTC
Labels: Accepted, Dashboard, Priority: Low, bug
