### ISSUE TITLE
Text Widget with legend image has problem with panels on the right

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3887] opened 2019-06-28 10:23 UTC
### Description
legend image hides when a right panel is opened

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- Chrome  75.0.3770.100 
- Brave  0.65.121 Chromium: 75.0.3770.100

*Steps to reproduce*

- open a new map 
- create a text widget with an image
IMPORTANT: the widget should be wide enough to not show the horizontal scrollbar and the vertical scrollbar must be visible 
- open catalog / trigger gfi
- close the opened panel

**You can use [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10632) map to easily replicate the issue.**

*Expected Result*

- to see again the text widget 

*Current Result*

- an empty/blank widget is presented
![Genova - legend wigdet and catalog problem](https://user-images.githubusercontent.com/11991428/60335859-26b8b600-999f-11e9-93c7-7def4368eb33.gif)

### Other useful information (optional):

when trying to resize the widget, it refreshes and it appears again.

**notes about EDGE 42.17134.1.0**

- it does not access the site if im connected to the vpn
- it appears also a horizontal scrollbar
![image](https://user-images.githubusercontent.com/11991428/60335467-4b605e00-999e-11e9-8cf6-fdcef43245c8.png)

It is also possible to view two horizontal scrollbar
![image](https://user-images.githubusercontent.com/11991428/60337002-240b9000-99a2-11e9-8b0e-1fddbac0a554.png)

**Comment by tdipisa** [comment] 2019-07-18 09:16
This seems to be solved in DEV, please test.

**Comment by gioscarda** [comment] 2019-07-18 15:07
That problems still exist in DEV.
I saved two map in which it is possible to replicate those scenarios:

1. [this map](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/10443) reproduce the empty/blank content after GFI/catalog --> click on the map to trigger GFI (or open the catalog), close the window and see the widget content

2. [this map](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/10447) reproduce the double horizontal scroll bar --> see the widget

**Comment by offtherailz** [comment] 2019-08-09 14:13
It works for me with chrome 70.0.3538.67

**Comment by tdipisa** [comment] 2021-08-03 11:27
Closed in favor of #7177

**Closed by tdipisa** 2021-08-03 11:27 UTC
Labels: Accepted, Good first issue, Priority: Medium, Widgets, bug
