### ISSUE TITLE
Popup not opens with URL parameter GFI

### ISSUE THREAD

**Issue by jusabatier** [geosolutions-it/MapStore2#8697] opened 2022-10-14 08:13 UTC
## Description
I just upgraded to [2022.02.00-RC2-geOrchestra](https://github.com/georchestra/mapstore2-georchestra/releases/tag/2022.02.00-RC2-geOrchestra) which add the 'Simplifying query parameters' functions.

I tested it, but when a context is configured to open GFI in a popup, and use GFI URL's params, the popup not open on page load.

Identifier plugin's configuration in the context : 

```
{
  "cfg": {
    "showInMapPopup": true,
    "disableCenterToMarker": true,
    "showHighlightFeatureButton": true,
    "viewerOptions": {
      "container": "{context.ReactSwipe}"
    }
  },
  "override": {
    "Toolbar": {
      "position": 11
    }
  }
}
```

## How to reproduce
=> quick example : https://geoportail.lepuyenvelay.fr/mapstore/#/context/TestPopup?addLayers=website:points_de_vente_libelle;gpvgs&mapInfo=website:points_de_vente_libelle&mapInfoFilter=%22id=15%22
=> Other method
- On your own platform setup a context with Identifier configured to use popup
- Use the GFI URL's parameters on this context's layer

*Expected Result*
The targeted feature's GFI result should open in a popup

*Current Result*
Only the marker appear, but not the popup

- [x] Not browser related

**Comment by tdipisa** [comment] 2022-10-18 15:20
duplicate of #8578

**Closed by tdipisa** 2022-10-18 15:20 UTC
Labels: bug, investigation
