### ISSUE TITLE
Problems when Tile Loading fails

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore2#223] opened 2015-10-13 12:10 UTC
If a tile fails to load for some reason application never tries to reload.
This produces an incomplete map. [i.e.](http://www.screencast.com/t/U8h6DBz19t)

**Comment by allyoucanmap** [comment] 2017-01-26 15:15
I reproduced this issue in chrome (Google Chrome 56.0.2924.76).
I activated the dev tools that let me to block a request for a single tile.

![0](https://cloud.githubusercontent.com/assets/19175505/22336209/b9ae6f48-e3e1-11e6-99a3-7bad581d36d1.png)

When I activated the request the tile isn't loaded yet.

![1](https://cloud.githubusercontent.com/assets/19175505/22336229/c8fcb9f0-e3e1-11e6-85f3-892b087ce1af.png)

I noticed that leaflet and openlayers don't refresh immediatly the tile layer on drag event but both need to get a render distance limit to redraw the tiles. (event type 'dragend' in leaflet, 'moveend' in openlayers)

![2](https://cloud.githubusercontent.com/assets/19175505/22336260/deb85fd8-e3e1-11e6-892f-5d659099ebc6.gif)

I tried to call a function to refresh/redraw after every 'dragend'/'moveend' but that comprise the render quality with screen flickering

```
// example in leaflet
this.map.on('dragend', () => {
	this.map.eachLayer( (layer) => {
		if (layer instanceof L.TileLayer) {
			layer.redraw();
		}
	});
	this.map.on('mousemove', this.mouseMoveEvent);
});
```

An implementation could be to add a boolean to the layer to detect the missing tile.

```
// example in leaflet
this.map.on('dragend', () => {
	this.map.eachLayer( (layer) => {
		if (layer instanceof L.TileLayer && layer.hasTileError) {
			layer.redraw();
		}
	});
	this.map.on('mousemove', this.mouseMoveEvent);
});
```

.hasTileError doesn't exist now.
The problem still remain in the case of missing url and the event will continue ask for refresh/radraw with the rendering problem described below.
I think that the rendering of leaflet and openlayers are just optimized for this situations.

**Comment by offtherailz** [comment] 2017-01-30 11:04
Thank you for your investigation. I think it not so easy to reproduce this issue in the real world, and it is hard to fix, adding complexity. 
Nobody else noticed issues like this on the various MS2 installations, so for now we assign to this issue a low priority. In the case we notice again this issue, we can follow your suggestion to fix it.

**Comment by offtherailz** [comment] 2017-10-19 07:48
it's been a long time since this issue was noticed. Don't know if it is really meanful now. Can we close it?

**Closed** 2017-12-15 09:05 UTC
Labels: enhancement, LeafLetJS, OL3, Priority: Low, task
