### ISSUE TITLE
Move the `paramActions` object from `epics/queryparams.js`

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#8308] opened 2022-06-07 16:50 UTC
Some logic to parse query params for creating maps with external parameters (expressed in the query string) resides into the `epics/queryparams.js` file. Whilst this could make sense since the resulting object is an array of actions run by epics (i.e. with the `Rx.Observable.from([])` method), it may not be appropriate for exporting, since the variable `paramActions` isn't an epic in its strict sense. 

see https://github.com/geosolutions-it/MapStore2/pull/8291#discussion_r890987588

**Comment by alexander-fedorenko** [comment] 2022-07-05 13:58
Hi @ElenaGallo 
I quickly checked what causes this behavior and it is due to incorrect condition check at this line: https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/QueryParamsUtils.js#L114
"roll" parameter is required to exist for cesium orientation action to trigger and in this case parameter is skipped because ternary returns false part of the expression. This is not regression, but logic needs to be modified to properly process numeric 0 value.

Please create new ticket and assign it on me. Thanks!

**Comment by ElenaGallo** [comment] 2022-07-05 14:16
@alexander-fedorenko here the new ticket: https://github.com/geosolutions-it/MapStore2/issues/8388

**Closed** 2022-07-05 14:18 UTC
Labels: enhancement, Priority: Low, Accepted, Internal, Good first issue
