### ISSUE TITLE
Some problems on creating / modifying geometry

### ISSUE THREAD

**Issue by GeoTob** [geosolutions-it/MapStore2#5575] opened 2020-07-02 06:02 UTC
## Description
When using the "attribute table" view to modify a WFS layer on an OpenLayers-based map, users are unable to persist a feature's geometry, nThis apply to new features and to modifying existing features. We have only tested point features. 

### New Feature
- Log in to MS2
- Open a map through openlayers
- Open the attribute table on a point layer
- Open edit mode
- Create a new feature and try to save it

### Existing Feature
- Log in to MS2
- Open a map through openlayers
- Open the attribute table for a point layer
- Open edit mode
- Modify the geometry on an existing feature
- Save

*Expected Result*
### New Feature
- The feature will be created without a geometry

### Existing Feature
- The feature will be updated with the new geometry

*Current Result*
### New Feature
- The feature will be created with a geometry

### Existing Feature
- The feature retains the old geometry

- [x] Not browser related

## Other useful information
- All works fine on leaflet maps
- Looking at the WFS request, the `<wfs:Insert>` block includes all attributes __except__ the geometry attribute. The `<wfs:Update>` block contains the geometry without a value:
```
        <wfs:Property>
            <wfs:Name>wkb_geometry</wfs:Name>
            <wfs:Value></wfs:Value>
        </wfs:Property>
```

From @tdipisa:
>I've created [this map](https://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/26734) on our DEV to replicate the issue and to quickly find a fix.

**Comment by tdipisa** [comment] 2020-07-02 08:42
Dear @GeoTob, I've checked what you have reported in our DEV instance on both polygon and point features and it is working fine, I was unable to reproduce the error you have reported. 

![grid_2](https://user-images.githubusercontent.com/1280027/86336817-a16e7e00-bc50-11ea-84d9-240314665a56.gif)

I'm wondering if your problem is related to your installation, are you using an older version of MS maybe affected by this bug? If yes, which version?
Anyway, we have two mailing list available (users and developers) if you have to raise questions, you can subscribe [here](https://mapstore2.geo-solutions.it/mapstore/#/) if you want. Thank you so much.

**Comment by GeoTob** [comment] 2020-07-03 08:05
@tdipisa I'm convinced there is an issue here that warrants investigation and fixing.

So today I've cloned a clean copy of 2020.01.01 _and_ the latest master, built both and pointed them at our production geostore - same problem. 

I've then used the default the geostore war and an empty GeoServer instance running just the default demo data to rule out configuration issues on our end.

This is where it got interesting - the `sf:bugsites`, `tiger:poly_landmarks` and `topp:tasmania_roads` datasets just work like your gif above, the `topp:tasmania_cities`layer does not work (the issue I described earlier) - when creating a geometry, the cursor just drags the map rather than creating a point. Note again that other datasets seem to work fine. All layers are published with the same permissions. 

I think this should be investigated further..

**Comment by tdipisa** [comment] 2020-07-03 09:05
Dear @GeoTob, thank you for this new information. Now I'm able to replicate the issue, it was helpful to understand what the specific use case was, since it looks like a problem related to a specific dataset (tasmania_cities). I'm moving this issue to the next milestone of minor release for an investigation and a possible fix. Thank you for reporting this.

**Comment by alistairjmcintyre** [comment] 2020-07-06 00:49
I've been investigating this also alongside @GeoTob.

I found that the GeoJSON objects that MapStore is trying to change are quite different between Leaflet and OpenLayers. 

In Leaflet, the requests work, and in OpenLayers they fail. Here's examples for the GeoJSON:
```
OpenLayers:
[
  {
    "id": "road_events.38",
    "updated": {
      "geometry": {
        "type": "GeometryCollection",
        "geometries": [
          {
            "type": "MultiPoint",
            "coordinates": [
              [
                177.09205627441406,
                -38.76746885907018
              ]
            ]
          }
        ]
      }
    }
  }
]


Leaflet:
[
  {
    "id": "road_events.38",
    "updated": {
      "geometry": {
        "type": "MultiPoint",
        "coordinates": [
          [
            177.062531,
            -38.77657
          ]
        ]
      }
    }
  }
]
```

I added a small bit of code to this [method](https://github.com/geosolutions-it/MapStore2/blob/b44d9a5e18be63a2e29e31d6e9a9bfe74426aac6/web/client/epics/featuregrid.js#L120) that grabs the first geometry and returns that if the change is a `GeometryCollection`.

I think there's probably a better fix, but it might hint towards whatever is causing this issue.

**Closed** 2020-07-27 12:50 UTC
Labels: Accepted, Priority: High, bug
