### ISSUE TITLE
Resource Category not found [name:CONTEXT]

### ISSUE THREAD

**Issue by DavidGhedini** [geosolutions-it/MapStore2#6955] opened 2021-06-07 23:41 UTC
## Description
When saving a Context, it displays "Context Saving Failed - Unknown Error"

## How to reproduce
Save a new Context

*Current Result*
"Context Saving Failed - Unknown Error"

## Log output
-------------------------------------- 
INFO   2021-06-07 23:38:10.432   RESTServiceImpl.extractAuthUser() - Accessing service with user admin and role ADMIN 
WARN   2021-06-07 23:38:10.436   WebApplicationExceptionMapper.toResponse() - WebApplicationException has been caught : Resource Category not found [name:CONTEXT] 
INFO   2021-06-07 23:38:10.437   AbstractLoggingInterceptor.log() - Outbound Message
---------------------------
ID: 48
Response-Code: 404
Content-Type: text/plain
Headers: {Cache-Control=[no-cache], Expires=[-1], Content-Type=[text/plain], Date=[Mon, 07 Jun 2021 23:38:10 GMT]}
Payload: Resource Category not found [name:CONTEXT]

**Comment by offtherailz** [comment] 2021-06-08 16:16
Hi, thank you for your feedback. 
This is an typical issue that happens during an update, when the database has not been aligned correctly. (If you are updating an existing MapStore, make sure to follow the [migration guidelines](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide.html))

So I suggest to write to the maling lists ([users](https://groups.google.com/g/mapstore-users) or [developers](https://groups.google.com/g/mapstore-developers)) to discuss your problem, contextualizing the reason of the problem and identifying if it is an effective bug or a problem of update. 

I'm closing this issue for the moment, we can re-open it if the bug if confirmed. Thank you for your patience.

**Closed by offtherailz** 2021-06-08 16:16 UTC
Labels: bug

**Comment by DavidGhedini** [comment] 2021-06-11 15:33
For anyone hitting the same issue, the geostore.gs_categories table should contain the rows below:
"1" "MAP"
"2" "THUMBNAIL"
"3" "DETAILS"
"4" "DASHBOARD"
"5" "GEOSTORY"
"6" "CONTEXT"
