### ISSUE TITLE
Clean up warnings in the console

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5702] opened 2020-07-27 07:42 UTC
## Description

As reported by andrea in [this](https://groups.google.com/forum/#!topic/mapstore-users/olJ2kp_nDKY) thread we have a lot of react WARNINGS in the console.
They are not a problem most of the time, but we should go and do a clean up because it could help improve performance and robustness

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
They are visible only in development mode i.e "npm start"
We should have a tour of al the functionalities to see if we can remove the majority of them possibly adding a test or by checking that changing the type of a property all works correctly and that no new warning is generated

**Comment by tdipisa** [comment] 2021-03-10 16:59
duplicate of #6614

**Closed by tdipisa** 2021-03-10 16:59 UTC
Labels: Priority: Medium, enhancement
