### ISSUE TITLE
Install WPS Download process on GS-Stable for testing purposes.

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#6153] opened 2020-11-02 16:53 UTC
We need the [Geoserver WPS Download](https://docs.geoserver.org/stable/en/user/community/wps-download/index.html) community module installed in GeoSolutions [gs-stable](http://gs-stable.geo-solutions.it/geoserver) for development purposes.
We can consider to limit the access to that process only to certain users belonging to the MapStore **geosolutions** and **testers** groups. This plugin is needed for the development of the new MapStore download tool (see #6144).

**Comment by randomorder** [comment] 2020-11-03 09:31
![image](https://user-images.githubusercontent.com/5264230/97968665-434cd580-1dbf-11eb-9c67-1e33c62135cf.png)

just need to configure it now
![image](https://user-images.githubusercontent.com/5264230/97968974-a9d1f380-1dbf-11eb-9a92-7e3122189da4.png)

Moving to test @tdipisa

**Comment by tdipisa** [comment] 2020-11-03 10:17
@randomorder WPS processes was not configured. I put the config below:

![image](https://user-images.githubusercontent.com/1280027/97972290-94ab9380-1dc4-11eb-93e3-42fcdc4e4875.png)

I tested using a sample request from the GeoServer official documentation and I got this exception:

```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://gs-stable.geo-solutions.it/geoserver/schemas/ows/1.1.0/owsAll.xsd">
    <ows:Exception exceptionCode="NoApplicableCode">
        <ows:ExceptionText>Unknown process gs:Download</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

Are all slaves currently aware of the security config?

**Comment by randomorder** [comment] 2020-11-03 10:25
> @randomorder WPS processes was not configured. I put the config below:
> 
> ![image](https://user-images.githubusercontent.com/1280027/97972290-94ab9380-1dc4-11eb-93e3-42fcdc4e4875.png)

Yes, I did that too

> Are all slaves currently aware of the security config? Without specifying security restrictions is seems to work

There's only one instance

>  Should we tune a bit the authentication filters to use WPS with authkey?

No idea

**Comment by tdipisa** [comment] 2020-11-03 11:14
@randomorder np thank you.
authkey I've used through postbam was not properly set, not it is recognized by GeoServer but I have the following error while performing the download request (sample request [here](https://docs.geoserver.org/stable/en/user/community/wps-download/rawDownload.html#sample-request)):

```
2020-11-03 11:03:44,357 WARN [geotools.xsd] - Sax parser property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' not recognized.  Xerces version is incompatible.
2020-11-03 11:03:44,425 ERROR [wps.executor] - Process execution failed
org.geotools.process.ProcessException: java.lang.IllegalArgumentException: Illegal argument: "type=null".
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:472)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:621)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:50)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:224)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:192)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Illegal argument: "type=null".
	at org.geotools.coverage.TypeMap.map(TypeMap.java:394)
	at org.geotools.coverage.TypeMap.getSize(TypeMap.java:340)
	at org.geoserver.wps.gs.download.RasterEstimator.execute(RasterEstimator.java:220)
	at org.geoserver.wps.gs.download.DownloadEstimatorProcess.execute(DownloadEstimatorProcess.java:188)
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:299)
	... 12 more
```

We should at least someone to check if the sample request is correct or if there are problems with the WPS.

**Comment by nmco** [comment] 2020-11-03 17:47
@jemacchi can you have a look at this one? Let's spend MAX 1 hour, as usual let's start whit an investigation. 

@tdipisa what's the project code for this?

**Comment by jemacchi** [comment] 2020-11-03 18:30
@nmco taking a look now. Could you please @tdipisa  share credentials for  http://gs-stable.geo-solutions.it/geoserver/web ? (first time I access to this environment. Thanks)

**Comment by simboss** [comment] 2020-11-03 18:33
I shared them with you privately.

**Comment by jemacchi** [comment] 2020-11-03 19:37
I have tested same steps as @tdipisa (getting same results). 
Just to ensure that it was not a problem with authentication, removed permissions for identifier gs:Download, and got same results again (that is, getting same error as [here](https://github.com/geosolutions-it/MapStore2/issues/6153#issuecomment-721053962))

Then tested on local geoserver enviroment the example from [here](https://docs.geoserver.org/stable/en/user/community/wps-download/rawDownload.html#sample-request) ) , without any permission handling, adding profiles wps and wps-download, and got this result:

```
org.geoserver.wps.WPSException: Could not parse XML request.
	at org.geoserver.wps.xml.v1_0_0.WpsXmlReader.read(WpsXmlReader.java:54)
	at org.geoserver.ows.Dispatcher.parseRequestXML(Dispatcher.java:1598)
	at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:699)
	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:255)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:70)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:77)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXException: Entity resolution disallowed for file:/prg/geosolutions/C174-IOSB_Fraunhofer-2019-SUPPORT/geotools/modules/extension/xsd/xsd-wps/target/classes/org/geotools/wps/wpsAll.xsd
	at org.geotools.util.PreventLocalEntityResolver.resolveEntity(PreventLocalEntityResolver.java:113)
	at org.geotools.xsd.impl.ParserHandler.resolveEntity(ParserHandler.java:276)
	at com.sun.org.apache.xerces.internal.util.EntityResolver2Wrapper.resolveEntity(EntityResolver2Wrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1081)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:654)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2432)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1769)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:742)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.geotools.xsd.Parser.parse(Parser.java:184)
	at org.geotools.xsd.Parser.parse(Parser.java:139)
	at org.geoserver.wps.xml.v1_0_0.WpsXmlReader.read(WpsXmlReader.java:52)
	... 93 more

```

The example as it's seems not to be working as mentioned in documentation.

**Comment by jemacchi** [comment] 2020-11-03 19:58
@simboss @simboss 
Update: in local environment when removing GT projects from eclipse IDE, then the   Entity resolution disallowed  conflict disappear (I found comments about that like [these](http://osgeo-org.1560.x6.nabble.com/IntelliJ-users-how-do-you-handle-quot-Entity-resolution-disallowed-for-file-home-aaime-devel-git-gt--td5346510.html).

**Comment by simboss** [comment] 2020-11-03 20:00
You are running from the IDE I guess and this sometimes gives issues, check around for similar issues

There is also work done in the past the past over entity resolution limitations for securityt reasons but I doubt this is your case.

**Comment by simboss** [comment] 2020-11-03 20:01
> @simboss
> Update: in local environment when removing GT projects from eclipse IDE, then the Entity resolution disallowed conflict disappear (I found comments about that like [these](http://osgeo-org.1560.x6.nabble.com/IntelliJ-users-how-do-you-handle-quot-Entity-resolution-disallowed-for-file-home-aaime-devel-git-gt--td5346510.html).

Good, please dig a little further than the obvious and what google can tell us already before reporting ;)

**Comment by jemacchi** [comment] 2020-11-03 20:26
Same thing. On local enviroment, error is still pointing to an **illegal argument type=null** 

```
Request: getServiceInfo
03 nov. 17:23:52 ERROR [wps.executor] - Process execution failed
org.geotools.process.ProcessException: java.lang.IllegalArgumentException: Argumento invalido: "type=null".
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:472)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:621)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:50)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:224)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:192)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalArgumentException: Argumento invalido: "type=null".
	at org.geotools.coverage.TypeMap.map(TypeMap.java:404)
	at org.geotools.coverage.TypeMap.getSize(TypeMap.java:350)
	at org.geoserver.wps.gs.download.RasterEstimator.execute(RasterEstimator.java:220)
	at org.geoserver.wps.gs.download.DownloadEstimatorProcess.execute(DownloadEstimatorProcess.java:188)
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:299)
	... 12 more
```

**Comment by jemacchi** [comment] 2020-11-03 20:43
@simboss 

Error is generated in line 220 at this [file](https://github.com/geoserver/geoserver/blob/9dec8fa23e86893aba71a25e448803f80c7b580e/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterEstimator.java#L220)   since   **coverageDimensionInfoList.get(i).getDimensionType()** is null. Then getSize() call fails.

Tested with different raster files and it shows same error.

**Comment by jemacchi** [comment] 2020-11-03 20:58
@simboss  @tdipisa 
Testing with different raster layers (from default data_dir dataset) I found that if I edit a layer, and update the bands definition here:
![image](https://user-images.githubusercontent.com/1171099/98039589-af4e2e80-1dfd-11eb-9bbe-895fc68c650d.png)

Then request to WPS, gs:Download as mentioned in the example, it start working.

Solution: please refresh/update layers bands definition before calling the service.

**Comment by simboss** [comment] 2020-11-03 21:00
@jemacchi this looks like a regression.
Can you show the before/after situation with the band details widget?

We should make the code more robust.

Can you also open a JIRA report for this and paste it here so that we decide what to do?

**Comment by nmco** [comment] 2020-11-03 22:47
@tdipisa what code should be used?
C183 | ALMAVIVA |  
-- | -- | --
  |   | C183-ALMAVIVA-2020-GeoNode-DEV
  |   | C183-ALMAVIVA-2020-GeoNode-SUPPORT

**Comment by simboss** [comment] 2020-11-03 22:57
dev

**Comment by tdipisa** [comment] 2020-11-04 09:19
@nmco C183-ALMAVIVA-2020-GeoNode-DEV

**Comment by nmco** [comment] 2020-11-04 13:21
So @tdipisa looks like we have a workaround: _Solution: please refresh/update layers bands definition before calling the service._ 

That say @jemacchi, so if I understood correctly it means that currently if we are running a GeoServer 2.18.x we need to explicitly refresh all layers bands definitions?  Then this looks very much like a regression. 

Can you spend 1 hour checking what cause this regression? A few tips: Is this reproducible whit a 2.18.1 GeoServer? 2.17.x GeoServer? What introduced this regression?

**Comment by jemacchi** [comment] 2020-11-04 13:25
Yes, it's as you describe @nmco . It's required to refresh layers (that is the workaround that worked)
I will take a look and create a new ticket with that information asap.

**Comment by nmco** [comment] 2020-11-04 13:27
Changing my mind, for now lets create a JIRA ticket in GeoServer describing the problem and a correspond ticket in https://github.com/geosolutions-it/geoserver, then we will decide how to proceed.

**Comment by tdipisa** [comment] 2020-11-04 14:52
Thank you for this @nmco and @jemacchi. Mine was just a first quick test to check the WPS download to ensure it is working fine for the developments we have to do for MS. If the problem I found is not so blocking for MS developments, there is no rush with this, feel free @nuno to schedule a fix as you prefer.
We are starting the development of a download tool to enrich the MS capabilities by using the WPS Download process. I think we will be able to identify other possible issues with the WPS only during developments and so schedule eventual fixes accordingly.

**Comment by tdipisa** [comment] 2020-11-04 14:55
I think we can close this issue for the moment.

**Comment by jemacchi** [comment] 2020-11-05 03:23
> @jemacchi this looks like a regression.
> Can you show the before/after situation with the band details widget?
> 
> We should make the code more robust.
> 
> Can you also open a JIRA report for this and paste it here so that we decide what to do?

@simboss 
Here capture of  nurc:Img_Sample  before forcing update (to make gs:Download to work)

![image](https://user-images.githubusercontent.com/1171099/98192765-63cd7a80-1efa-11eb-872b-c9b4f20f2846.png)

And here capture of how same layer setting looks after update (so gs:Download started to work)
![image](https://user-images.githubusercontent.com/1171099/98192810-82337600-1efa-11eb-9c3f-2d35d7032ebd.png)


[Here](https://osgeo-org.atlassian.net/browse/GEOS-9785) the associated ticket in Geoserver JIRA.

**Closed** 2020-11-09 09:20 UTC
Labels: Priority: Blocker, Project: C183
