### ISSUE TITLE
Annotations - Circle geometry issue with radius

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8474] opened 2022-08-12 07:54 UTC
## Description

When the circle is drawn, the radius is not inserted and if the radius is entered by the user, a gray error page appears. 

## How to reproduce

-  Open a map
- Open the Annotations panel
- Click on +
- Follows the steps in the gif below:
![circle](https://user-images.githubusercontent.com/56537133/184310119-209b5bfc-5308-472b-9975-64f2be3bb72e.gif)

*Expected Result*

 The radius measurement appears on the panel

*Current Result*

The radius measurement does not appear and if the radius is entered by the user, a gray error page appears. 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment] 2022-08-31 15:49
@tdipisa this probably is a regression due to #8082 being merged with #8325

once the revert is merged i'll test again

**Comment by MV88** [comment] 2022-08-31 16:26
@tdipisa I confirm what reported above

@ElenaGallo please re-test this issue in DEV

**Closed** 2022-09-05 08:43 UTC
Labels: bug, Accepted, Internal
