### ISSUE TITLE
Feature info from search has application/json info format hardcoded, while it should not

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6507] opened 2021-02-03 17:10 UTC
## Description

the problem is that gfi from search ignores the info format defined for that specific layer, or the global one

open a map where a search services has this configuration or [this](http://localhost:8081/?debug=true#/viewer/openlayers/880) map for austrocontrol project
![image](https://user-images.githubusercontent.com/11991428/106782111-1623f380-664a-11eb-9ae3-6db039ad34b4.png)

the text description should change to 
"Identify panel will show up displaying information only for this layer"

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment] 2021-02-04 17:39
In this case the identify request is performed requiring a json output format and there is a specific reason for this since, generally speaking, multiple overlapping features can be present in the Identify point in map. For this reason, MapStore needs to be able to filter Identify results in order to show in the Identify panel only the exact feature clicked in the search result list: using a cql filter for the identify is something we have to evaluate for this case but it is suported only by GeoServer as a vendor option.

**Comment by tdipisa** [comment] 2021-03-10 16:41
Duplicate of #6609

**Closed by tdipisa** 2021-03-10 16:41 UTC
Labels: C125-2020-AUSTROCONTROL-Map2Imp, enhancement
