### ISSUE TITLE
Mobile - chart widget display problem

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4388] opened 2019-10-22 14:49 UTC
### Description
The chart types are not all inside the display

![issue5 1](https://user-images.githubusercontent.com/56537133/67298280-51e58900-f4eb-11e9-8f10-f18433bc16bd.gif)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

No browser related 

*Steps to reproduce*

- Click on a Deshboard
- Click Widget
- Click Chart
- Add a layer
- Select the Chart type

*Expected Result*

The chart is all in the display

*Current Result*

The chart type is not all inside the display

### Other useful information (optional):

Same problem in the Counter Widget

**Comment by offtherailz** [comment] 2020-07-20 13:54
@ElenaGallo I think the feature you are showing in the gif should not be available for mobile.
So more then a responsiveness problem, the problem is how you was able to open that from the emulator.

**Comment by ElenaGallo** [comment] 2020-07-20 14:30
@offtherailz It is no longer possible to open a new dashboard on mobile, so this issue is no longer applicable now.

**Comment by offtherailz** [comment] 2020-07-21 12:31
correct @ElenaGallo, I'm going to close this PR too.

**Closed by offtherailz** 2020-07-21 12:31 UTC
Labels: Mobile, Priority: High, bug
