### ISSUE TITLE
User Guide - Add new Annotations UI

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9448] opened 2023-09-14 13:56 UTC
## Description

Add new Annotations UI and 3D mode option on [Annotations](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/annotations/) section
*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Related to #9447

**Comment by tdipisa** [comment] 2023-09-29 13:32
Duplicate of #9472. Closing this.

**Closed by tdipisa** 2023-09-29 13:32 UTC
Labels: duplicate, Documentation, annotations, User Guide, 3D, C027-COMUNE_FI-2023-SUPPORT
