### ISSUE TITLE
Opening a 3D map causes an error

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10211] opened 2024-04-16 15:54 UTC
## Description

The gray error page appears when opening an existing map or a new map after a 3D map has just been opened

https://github.com/geosolutions-it/MapStore2/assets/56537133/39c0d9b3-10d3-4952-9b89-943c9b3b11d4

## How to reproduce

-  Open a 3D map
-  Back to home Page
- Open a new map or another map

*Expected Result*

The map opens
*Current Result*

The gray error page apperas

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

On DEV e QA

The error in console is the following one:

```
mapstore2.js?c357fb33cb80d588ba37:2 TypeError: Cannot read properties of undefined (reading 'x')
    at H.componentDidMount (4304.c357fb33cb80d588ba37.chunk.js:1:14599)
    at Cl (mapstore2.js?c357fb33cb80d588ba37:2:3453942)
    at t.unstable_runWithPriority (mapstore2.js?c357fb33cb80d588ba37:2:4397959)
    at Zo (mapstore2.js?c357fb33cb80d588ba37:2:3399477)
    at Tl (mapstore2.js?c357fb33cb80d588ba37:2:3450501)
    at ul (mapstore2.js?c357fb33cb80d588ba37:2:3440621)
    at mapstore2.js?c357fb33cb80d588ba37:2:3399768
    at t.unstable_runWithPriority (mapstore2.js?c357fb33cb80d588ba37:2:4397959)
    at Zo (mapstore2.js?c357fb33cb80d588ba37:2:3399477)
    at Ko (mapstore2.js?c357fb33cb80d588ba37:2:3399713)
    at Vo (mapstore2.js?c357fb33cb80d588ba37:2:3399648)
    at ol (mapstore2.js?c357fb33cb80d588ba37:2:3437120)
    at Object.enqueueSetState (mapstore2.js?c357fb33cb80d588ba37:2:3404345)
    at w.setState (mapstore2.js?c357fb33cb80d588ba37:2:4078154)
    at map.c357fb33cb80d588ba37.chunk.js:1:14424
onError @ mapstore2.js?c357fb33cb80d588ba37:2
value @ mapstore2.js?c357fb33cb80d588ba37:2
i.componentDidCatch.r.callback @ mapstore2.js?c357fb33cb80d588ba37:2
vi @ mapstore2.js?c357fb33cb80d588ba37:2
yi @ mapstore2.js?c357fb33cb80d588ba37:2
Cl @ mapstore2.js?c357fb33cb80d588ba37:2
t.unstable_runWithPriority @ mapstore2.js?c357fb33cb80d588ba37:2
Zo @ mapstore2.js?c357fb33cb80d588ba37:2
Tl @ mapstore2.js?c357fb33cb80d588ba37:2
ul @ mapstore2.js?c357fb33cb80d588ba37:2
(anonymous) @ mapstore2.js?c357fb33cb80d588ba37:2
t.unstable_runWithPriority @ mapstore2.js?c357fb33cb80d588ba37:2
Zo @ mapstore2.js?c357fb33cb80d588ba37:2
Ko @ mapstore2.js?c357fb33cb80d588ba37:2
Vo @ mapstore2.js?c357fb33cb80d588ba37:2
ol @ mapstore2.js?c357fb33cb80d588ba37:2
enqueueSetState @ mapstore2.js?c357fb33cb80d588ba37:2
w.setState @ mapstore2.js?c357fb33cb80d588ba37:2
(anonymous) @ map.c357fb33cb80d588ba37.chunk.js:1
Promise.then (async)
(anonymous) @ map.c357fb33cb80d588ba37.chunk.js:1
UNSAFE_componentWillMount @ map.c357fb33cb80d588ba37.chunk.js:1
Ci @ mapstore2.js?c357fb33cb80d588ba37:2
Ba @ mapstore2.js?c357fb33cb80d588ba37:2
rl @ mapstore2.js?c357fb33cb80d588ba37:2
El @ mapstore2.js?c357fb33cb80d588ba37:2
_l @ mapstore2.js?c357fb33cb80d588ba37:2
ul @ mapstore2.js?c357fb33cb80d588ba37:2
(anonymous) @ mapstore2.js?c357fb33cb80d588ba37:2
t.unstable_runWithPriority @ mapstore2.js?c357fb33cb80d588ba37:2
Zo @ mapstore2.js?c357fb33cb80d588ba37:2
Ko @ mapstore2.js?c357fb33cb80d588ba37:2
Vo @ mapstore2.js?c357fb33cb80d588ba37:2
hl @ mapstore2.js?c357fb33cb80d588ba37:2
Er @ mapstore2.js?c357fb33cb80d588ba37:2
mapstore2.js?c357fb33cb80d588ba37:2 TypeError: Cannot read properties of undefined (reading 'destroy')
    at H.componentWillUnmount (4304.c357fb33cb80d588ba37.chunk.js:1:17008)
    at mapstore2.js?c357fb33cb80d588ba37:2:3431104
    at as (mapstore2.js?c357fb33cb80d588ba37:2:3431145)
    at cs (mapstore2.js?c357fb33cb80d588ba37:2:3432908)
    at Cl (mapstore2.js?c357fb33cb80d588ba37:2:3452604)
    at t.unstable_runWithPriority (mapstore2.js?c357fb33cb80d588ba37:2:4397959)
    at Zo (mapstore2.js?c357fb33cb80d588ba37:2:3399477)
    at Tl (mapstore2.js?c357fb33cb80d588ba37:2:3450501)
    at ul (mapstore2.js?c357fb33cb80d588ba37:2:3440621)
    at mapstore2.js?c357fb33cb80d588ba37:2:3399768
    at t.unstable_runWithPriority (mapstore2.js?c357fb33cb80d588ba37:2:4397959)
    at Zo (mapstore2.js?c357fb33cb80d588ba37:2:3399477)
    at Ko (mapstore2.js?c357fb33cb80d588ba37:2:3399713)
    at Vo (mapstore2.js?c357fb33cb80d588ba37:2:3399648)
    at ol (mapstore2.js?c357fb33cb80d588ba37:2:3437120)
    at Object.enqueueSetState (mapstore2.js?c357fb33cb80d588ba37:2:3404345)
```

**Comment by MV88** [comment] 2024-04-19 10:44
not reproducible in dev at the moment, but only in qa, maybe is related to this
https://github.com/geosolutions-it/MapStore2/issues/10196

**Comment by tdipisa** [comment] 2024-04-19 12:06
> not reproducible in dev at the moment, but only in qa, maybe is related to this #10196

@MV88 that's the same for me. @ElenaGallo please retest also in QA once the backport PR for #10196 is deployed there.

**Comment by offtherailz** [comment] 2024-05-08 07:35
Closing because moved in done

**Closed by offtherailz** 2024-05-08 07:35 UTC
Labels: bug, Accepted, Internal
