### ISSUE TITLE
Missing documentation in developer documentation to start-up back-end

### ISSUE THREAD

**Issue by gennarobotta** [geosolutions-it/MapStore2#5712] opened 2020-07-29 09:47 UTC
-- **Edit By @offtherailz**
There is a missing command to run it locally. `mvn install in the root`. We should also mention in documentation the issue #5474  until is solved, to inform the users that the feature is not working.

-- End edit

## Description

Failed to start server, unresolved dependencies
## How to reproduce

download release MapStore2-2020.02.00 
extract 
in web subdirectory run  mvn jetty:run 

*Expected Result*
compile and start server

*Current Result*

Build Failure

- [x] Not browser related

## Other useful information
`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.354 s
[INFO] Finished at: 2020-07-29T11:37:51+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mapstore-web: Could not resolve dependencies for project it.geosolutions.mapstore:mapstore-web:war:1.0-SNAPSHOT: Failure to find it.geosolutions.mapstore:mapstore-backend:jar:1.0-SNAPSHOT in https://maven.geo-solutions.it was cached in the local repository, resolution will not be reattempted until the update interval of geosolutions has elapsed or updates are forced -> [Help 1]`

**Comment by offtherailz** [comment] 2020-07-29 15:02
We have an issue related to mvn:jetty run (#5474) but the error doesn't look the same.
Probably from the last release you may need to run` mvn install` in the root first, to build the missing artifact. Good to know, if confirmed we will add this to docuementation.
Anyway mvn:jetty-run is not working because of #5474. 
So Please use the alternative solution (tomcat) in the comment until #5474  is solved.

**Comment by gennarobotta** [comment] 2020-07-29 15:34
Thanks for the response.
`mvn install` has worked but as you mentioned it throw the error in #5474 
Can i use  -Pserveronly with tomcat too?

**Comment by offtherailz** [comment] 2020-07-29 16:19
Thanks for confirmation. We will add this directive to the documentation.
No, serverOnly is not mandatory anyway. 
You can run full mapstore in tomcat and use it as a back-end for your local environment.

**Comment by offtherailz** [comment] 2020-08-31 15:22
going to close this in favor of #5474 because #5719 adds also documentation

**Closed by offtherailz** 2020-08-31 15:22 UTC
Labels: Documentation, Priority: Medium, bug
