### ISSUE TITLE
Allow to set GetLegendGraphic options

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#4473] opened 2019-11-08 17:26 UTC
### Description
Add possibilities to set new options to improve legend in TOC:
- `hideEmptyRules`
- `countMatched`
- Other legend options (eg. the scale param)
http://gs-stable.geo-solutions.it/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=gs%3Any_roads&scale=10000

**Reference:**
https://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html#controlling-legend-appearance-with-legend-options

### Other useful information (optional):
Also FORMAT_OPTIONS could be added to customizable parameters

https://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html#content-dependent-legends

**Comment by offtherailz** [comment] 2020-01-07 16:18
Maybe in layer properties --> display tab we can add an inputbox or a tool to customize the legend (with a preview)

**Comment by PedG** [comment] 2020-02-06 14:23
I suppose it will be posible setting these pararameters in localConfig.json, won't be? (a default value for all layers that user can modify individualy later).

Furthermore maybe interesting in Catalog,  Advanced Setting, so when someone add layers from a WMS server all layers will use it, although they can edit in Layer properties as well.

That issue is crucial as you can see in [https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/3267](demo) as symbols for Invatamant layer are not legible. By the way ¿are you thinking how dealing with layers and rule descriptions with long names?

**Comment by tdipisa** [comment] 2021-06-11 08:21
duplicate of #5169

**Closed by tdipisa** 2021-06-11 08:21 UTC
Labels: Priority: High, enhancement
