### ISSUE TITLE
Dashboard - Malfunction of Closed groups button on map widget

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4480] opened 2019-11-12 11:13 UTC
### Description
On configure map options in the map widget it is not possible closed the folder.

![issue16](https://user-images.githubusercontent.com/56537133/68666415-2ed75380-0544-11ea-9fd4-15ce65e7304c.gif)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*
no browser related

*Steps to reproduce*
- open a new dashboard
- open the map widget
- select a map 

*Expected Result*

the 'close group' button closes the layers folder 

*Current Result*

the 'close group' button does not close the layers folder

**Comment by tdipisa** [comment] 2020-03-11 13:51
duplicate of #4709

**Closed by tdipisa** 2020-03-11 13:51 UTC
Labels: Priority: Medium, bug
