### ISSUE TITLE
WPS based Data Export

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6144] opened 2020-11-02 12:03 UTC
## Description

We want to extend the “Export Data” tool, that currently is only available for vector layers from the FeatureGrid component, with the following enhancements:

- overcome the limitation of WFS/WCS requests (heavy load on Geoserver, sync execution, etc.) using the [Geoserver WPS Download](https://docs.geoserver.org/stable/en/user/community/wps-download/index.html) community module
- export both vector and raster layers
- expose the export tool as a layer tool
- pave the path to more advanced options (ROI, GeoTiff writer options, etc.)

We are going to rely on the [Raw data download process for GeoServer](https://docs.geoserver.org/stable/en/user/community/wps-download/rawDownload.html).

### WPS Download client
MapStore already adopts WPS for some components (example data “aggregate” functionalities). We might therefore investigate if something from the existing tools can be reused or factored out to obtain a common base interface for any functionality that requires to interact with WPS processes.

The option to reuse something from previous implementations (MapStore1 with OL2) has been discarded since the technologies have changed too much meanwhile, and OL3/4 don’t support WPS natively anymore.

A critical enhancement to the current use cases in MapStore is the implementation of an asynchronous interface. This means that the following key points must be designed and implemented:

- download estimator request to validate the download request (gs:DownloadEstimator) according to the configured limits for the WPS process
- request async execution (gs:Download)
- track execution status
- manage execution results, which will be requested as “reference” results to be obtained as link to downloadable files

The execution request will use the following parameters (with more to come in the future):

- layerName 
- outputFormat 
- targetCRS 
- filter (only for vector data)
- ROI
- RoiCRS
- cropToROI 
- writing parameters 

First three parameters are those already adopted by the current “Export Data” window. 
The filter parameter will restrict the export to a subset of data. The filter will be defined with the already existing MapStore filter panel and/or (in case of vector layers) through the FeatureGrid filters.

The ROI+RoiCRS+cropToROI parameters will be used to support cropping the dataset to the map viewport.

The [writing parameters](https://docs.geoserver.org/stable/en/user/community/wps-download/rawDownload.html#writing-params) are especially useful for raster data to, for example, request a specific compression format or the tile sizes of the downloaded file.

### Important Note:
_The implementation of the WPS async interface client will be as generic as possible, so that it will be possible to adopt it for different processes and contexts with minimal effort. A specific business logic layer will be implemented on top of it for the specific purposes of the “data export” process._

### Export Data UI components
The current Export Data window can be reused for the time being, It will be launched by:

- the already available “export data” button from the FeatureGrid, with export data button replaced with glyphicon-download

![image](https://user-images.githubusercontent.com/571129/97861079-7cc00b00-1d03-11eb-90af-46533af7f528.png)

- a new button inside the layer toolbar (as already done for AustroControl)

![image](https://user-images.githubusercontent.com/571129/97865575-b8aa9e80-1d0a-11eb-89e1-b99000bed4e2.png)

### Important Note
_Currently the Export Data tool is using WFS: we need to include a preventive check to verify if the WPS process is available or not and enable the WPS UI part accordingly, otherwise the current one is provided to the user using WFS as it is now._

Two options will be visible to the user:

- “**crop dataset to current viewport**”: this will set the ROI and cropToROI execution parameters, that will clip the vector / crop the raster to the visible map viewport
- “**export filtered dataset” (ONLY FOR VECTOR LAYERS)** in case a global filter has been set and/or a filter has been set inside the FeatureGrid
“**advanced options“ (ONLY FOR RASTER LAYERS -for the moment)**:  collapsible area showing the following advanced parameters:
  - “Compression”: select box
    - Deflate
    - LZW
    - JPEG
    - ZLib
    - PackBits
    - CCITT RLE
  - “Tile height”: (numeric box)
  - “Tile width”: (numeric box)
  - "quality" (missing in the image below) which is a double in the range [0 : 1] where 0 is for worst quality/higher compression and 1 is for best quality/lower compression

![image](https://user-images.githubusercontent.com/571129/97863436-41bfd680-1d07-11eb-844f-21a48b31e829.png)

![image](https://user-images.githubusercontent.com/571129/97860374-4df56500-1d02-11eb-8fec-f08ff805645f.png)

![image](https://user-images.githubusercontent.com/571129/97863469-52704c80-1d07-11eb-8111-c12dcfee12e6.png)

### Execution status and Results management
Being an asynchronous execution we must keep track of the status and implement a panel to let the user inspect the export procedure status and download the final files.

Ideally the status should be bound to the user's session**, but this requires the support from a backend.
Session bound status will be developed at a future stage**. **For the moment the status will be only serialized to a cookie**, so that at least the user won't loose ongoing exports if he refreshes or closes / reopens the page.

From the UI/UX persepctive the proposal is to implement:

- toast messages / message boxes for immediate messages to the users:
  - DownloadEstimator negative response
  - Export started
  - Export failure
- a “tray icon” and a “export status panel” available from the status bar, to keep the user informed of status events

![image](https://user-images.githubusercontent.com/571129/97866054-7afa4580-1d0b-11eb-9360-c6f34370607d.png)

Clicking on the tray icon a “**Status window**” will be shown with the list of ongoing export processes (for all layers) and processed files.

![image](https://user-images.githubusercontent.com/571129/97865663-da0b8a80-1d0a-11eb-873f-95f1f3198fb8.png)

The window will show the submitted download requests, that can be in one of the following three states:

- **pending**: a spinner communicates the ongoing procedure
- **completed**: a “floppy icon” communicates the ability to download the generated file
- **failed**: clicking on the red “error icon” will show a message window explaining what happened (always high level messages for the end user only!)

A “bin icon” will provide the ability to cancel a pending request or remove a completed / failed download from the “Status window”.

Geoserver will retain the generated files only for a configurable amount of time. This means that a previous download might not be available anymore. When the “Status window” is made visible a request must be submitted by the client to check if the recorded files are still available. In case they have been removed by Geoserver, they must be removed from the client “Status window”.

## Other useful information

- Geoserver WPS module: https://docs.geoserver.org/stable/en/user/community/wps-download/index.html
- OGC WPS Standard: https://www.ogc.org/standards/wps

**Comment by giohappy** [comment] 2020-11-02 14:04
@simboss more details will be added inside the issues, but please add any additional consideration to the epic if you wish.

**Comment by simboss** [comment] 2020-11-02 16:51
@giohappy I did a quick review with @tdipisa.
I think it correctly capture everything. Good job!

**Comment by simboss** [comment] 2020-11-02 16:54
@tdipisa one thing to take into account.

This will be used also in GeoNode so we will have to account for that integration both in terms of the integration itself as well as the ability to properly propagate authkeys to work nicely for geonode integrations.

**Comment by ElenaGallo** [comment] 2020-11-25 09:59
It is not possible download the file from the Export data result panel. A security error appears on console:

> Mixed Content: The site at 'https://dev.mapstore2.geo-solutions.it/' was loaded over a secure connection, but the file at 'http://gs-stable.geo-solutions.it/geoserver/ows?service=WPS&version=1.0.0&request=GetExecutionResult&executionId=757f3559-83e4-48d3-b4fa-34db8f37d69f&outputId=result.zip&mimetype=application%2Fzip&authkey=0aba9add-fcc5-4ddc-ae6a-c872817a0c7f' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

**How to reproduce**
![download-error](https://user-images.githubusercontent.com/56537133/100212042-29f5ff80-2f0d-11eb-84d5-426866442c8a.gif)


*Current Result*
Exporting any type of data causes a security error therefore it is not possible to export the data localy

**Comment by tdipisa** [comment] 2020-11-25 10:37
@vlt1 I saw MS is using HTTP for some calls to GeoServer like:

- GetExecutionStatus
- GetExecutionResult

while in the layer configuration (in [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358)) there is  HTTPS set. Why this? I think a fix is needed here, in addition MS should also warn the user if the download is not possible for mixed content problems.

**Comment by tdipisa** [comment] 2020-11-25 11:10
@giohappy 
I've checked again and I found that the **GetExecutionStatus** request performed by MS using HTTPs:

https://gs-stable.geo-solutions.it/geoserver/wps?service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=ebd48fbd-f8db-40ff-b11e-841fe2bbec03&authkey=42a4e18a-deb2-4f0d-9115-0d121460a256

Has the following response:

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" service="WPS" serviceInstance="http://gs-stable.geo-solutions.it/geoserver/ows?authkey=42a4e18a-deb2-4f0d-9115-0d121460a256&amp;" statusLocation="http://gs-stable.geo-solutions.it/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionStatus&amp;executionId=ebd48fbd-f8db-40ff-b11e-841fe2bbec03&amp;authkey=42a4e18a-deb2-4f0d-9115-0d121460a256" version="1.0.0">
	<wps:Process wps:processVersion="1.0.0">
		<ows:Identifier>gs:Download</ows:Identifier>
		<ows:Title>Enterprise Download Process</ows:Title>
		<ows:Abstract>Downloads Layer Stream and provides a ZIP.</ows:Abstract>
	</wps:Process>
	<wps:Status creationTime="2020-11-25T11:00:56.038Z">
		<wps:ProcessSucceeded>Process succeeded.</wps:ProcessSucceeded>
	</wps:Status>
	<wps:ProcessOutputs>
		<wps:Output>
			<ows:Identifier>result</ows:Identifier>
			<ows:Title>Zipped output files to download</ows:Title>
			<wps:Reference href="http://gs-stable.geo-solutions.it/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionResult&amp;executionId=ebd48fbd-f8db-40ff-b11e-841fe2bbec03&amp;outputId=result.zip&amp;mimetype=application%2Fzip&amp;authkey=42a4e18a-deb2-4f0d-9115-0d121460a256" mimeType="application/zip"/>
		</wps:Output>
	</wps:ProcessOutputs>
</wps:ExecuteResponse>
```

Where GeoServer put HTTP in the **wps:Reference href**. This generates the mixed content issue. So I think there is a problem GS side for this.

@vlt1 as I said in the above comment anyway:

>in addition MS should also warn the user if the download is not possible for some reason like mixed content problems.

**Comment by tdipisa** [comment] 2020-11-25 11:15
I also have this error if I try to export a raster layer

![image](https://user-images.githubusercontent.com/1280027/100220461-b1487080-2f17-11eb-9355-9eee4c8c17cd.png)

**Comment by nmco** [comment] 2020-11-26 19:00
Looks like a bug in some of the URL mangler of GeoServer, @tdipisa if you wish to be fixed in GeoServer please open an issue in GeoServer and we will proposed an estimate and plan.

**Comment by tdipisa** [comment] 2020-11-27 12:13
> Looks like a bug in some of the URL mangler of GeoServer, @tdipisa if you wish this to be fixed in GeoServer please open an issue in GeoServer and we will proposed an estimate and plan.

@nmco Thank you so much. I've opened these new issues:
https://github.com/geosolutions-it/geoserver/issues/216
https://github.com/geosolutions-it/geoserver/issues/217

**Comment by tdipisa** [comment] 2020-11-27 12:20
@simboss below is a link to the current plugin documentation:
https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.LayerDownload

I've created also #6250 for a check of the plugin doc.

**Closed** 2020-12-17 11:55 UTC
Labels: Accepted, C183-ALMAVIVA-2020-GeoNode-DEV, Epic, New Feature, Priority: High
