### ISSUE TITLE
Add possibility to alias columns in the attribute table

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5895] opened 2020-09-18 09:50 UTC
## Description

![image](https://user-images.githubusercontent.com/11991428/93583081-aa473400-f9a3-11ea-93fe-3fa079e0f698.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

Since this can be implemented in various ways let's discuss the implementation details when this issue will be assigned
[link ](https://groups.google.com/g/mapstore-users/c/Ih3B8fnGrGo/m/k-mkKgoiBgAJ) to mail in google groups

**Comment by buhao75** [comment] 2020-09-18 09:54
Hi!
That would be a cool feature. 
Best regards, 
Michael

**Comment by catmorales** [comment] 2023-01-27 10:39
This improvement can be great for us too ,  
I have two avenues for reflections ;
- Is the alias name should be permanent after closing the attribute table  and in this case stored into  the user session (or other) ?
- Is the mapping between real name and aliases could be realized at plugin level by administrators  too for specific layers ?

**Comment by catmorales** [comment] 2023-01-27 16:27
Something like what you have developed  fotr tables in  dashboard functionnality could works:
![image](https://user-images.githubusercontent.com/4659829/215139354-37ce2bf7-d81d-4b70-b9b9-d3a33707abea.png)

**Comment by tdipisa** [comment] 2023-01-31 10:27
Doing what requested by the issue is obviously possible but we have to point out the following:

1.  The change cannot be done at Attribute Table level because we have to keep consistency across different tools that manage/visualize somehow the feature attributes: Visual Style Editor, Filter Layer tool, Identify tool etc. This means that aliases for feature attributes need to be controlled/centralized in Layers Settings

2. For transparency it is necessary to let the user always know the real attribute name in certain cases. Therefore, as it happen in QGIS for example, the real attribute name will appear in brackets (only inside a tooltip) when you move the mouse over the alias in the Attribute Table header
 
3. Since we are going to control aliases (we are not changing the real attribute name from MapStore), the real attribute name will be obviously used where needed (eg. OGC filters, SLDs, other OGC requests involving charts/widgets) in a transparent way. This means that from UI the user will see/select the alias name while the real name will be used for final requests to the remote services

4. The following constrains anyway exist:
   - MapStore cannot have control on Identify formats other than application/json for which it is possible to intervene on the output programmatically to show the alias instead of the real attribute name
   - Inside the Code Style Editor (the style text area) the real attribute name need to be anyway used

5. From Layer Settings it will be possible to set aliases to real attributes name through a kind of tabular view where a reload button will allow to reload the Feature Type schema on demand (eg. if an attribute name is changed server side) so that the user can set again the alias when needed

6. What already implemented for widgets can be maintained. The widget can inherit aliases defined at Layer Settings level giving the possibility to further change them at widget level. 

7. Each map will have its own setting of aliases

**Comment by tdipisa** [comment] 2023-04-14 15:05
Closed in favor of #9099

**Closed by tdipisa** 2023-04-14 15:05 UTC
Labels: enhancement
