### ISSUE TITLE
Allow custom tile provider to be specified fully in config.json

### ISSUE THREAD

**Issue by riaanvddool** [geosolutions-it/MapStore2#2309] opened 2017-10-19 12:46 UTC
Tile providers currently has to be specified in `MapStore2/web/client/utils/ConfigProvider.js`

For me to add a new tile provider (see MapBoxStyle below) I have to specify it as follows:

    MapBox: {
        url: '//api.tiles.mapbox.com/v4/{source}/{z}/{x}/{y}.png?access_token={accessToken}',
        options: {
            attribution:
                    'Imagery from <a href="http://mapbox.com/about/maps/">MapBox</a> &mdash; ' +
                    'Map data {attribution.OpenStreetMap}',
            subdomains: 'abcd'
        }
    },
    MapBoxStyle: {
        url: 'https://api.mapbox.com/styles/v1/mapbox/{source}/tiles/{z}/{x}/{y}?access_token={accessToken}',
        options: {
            attribution: 'Imagery from <a href="http://mapbox.com/about/maps/">MapBox</a>',
            subdomains: 'abcd'
        }
    },

I have now made a change in the MapBox submodule, instead of just changing a config item in my project. It would be better if I could add my custom tile provider to `MapStore2/config.json` as follows:

    "layers": [
      {
        "type": "tileprovider",
        "title": "MapBox Outdoors",
        "url": "https://api.mapbox.com/styles/v1/mapbox/{source}/tiles/{z}/{x}/{y}?access_token={accessToken}",
        "thumbURL": "/assets/img/MapBoxOutdoors.png",
        "provider": "MapBoxStyle",
        "accessToken": "pk.xxxxxxxxxxxxxxxxxxxxx",
        "name": "MapBoxOutdoors",
        "source": "outdoors-v10",
        "group": "background",
        "visibility": true
      },
      {
        "type": "osm",
        "title": "Open Street Map",
        "name": "mapnik",
        "source": "osm",
        "group": "background",
        "visibility": false
    },

This test fails because `MapBoxStyle` is not defined as a provider in `MapStore2/web/client/utils/ConfigProvider.js`. 

https://github.com/geosolutions-it/MapStore2/blob/36f4630407d0931c6b5b73387f4f140c156965fc/web/client/utils/TileConfigProvider.js#L11-L12

Using the `MapBox` provider and specifying a custom url in `config.json` does not replace the `MapBox` provider url with my custom url either.

Suggestion: 

1. Add a `Custom` provider to `MapStore2/web/client/utils/ConfigProvider.js`

<pre>    Custom: {
        url: '',
        options: {
            attribution: '',
            subdomains: ''
        }
    }
</pre>

2. Allow URL in `config.json` so that `Custom` provider's default URL is replaced:

<pre>
    "layers": [
      {
        "type": "tileprovider",
        "title": "MapBox Outdoors",
        "url": "https://api.mapbox.com/styles/v1/mapbox/{source}/tiles/{z}/{x}/{y}?access_token={accessToken}",
        "thumbURL": "/assets/img/MapBoxOutdoors.png",
        "provider": "Custom",
        "accessToken": "pk.xxxxxxxxxxxxxxxxxxxxx",
        "name": "MapBoxOutdoors",
        "source": "outdoors-v10",
        "group": "background",
        "visibility": true
      },
</pre>

This will need to allow `url` to be replaced:

https://github.com/geosolutions-it/MapStore2/blob/36f4630407d0931c6b5b73387f4f140c156965fc/web/client/utils/TileConfigProvider.js#L14-L17

**Comment by riaanvddool** [comment] 2017-10-20 10:51
PR #2313 provides interim solution

**Comment by mbarto** [comment] 2019-10-18 12:43
duplicate of #2310

**Closed by mbarto** 2019-10-18 12:43 UTC
Labels: Priority: Medium, enhancement
