### ISSUE TITLE
Strange/wrong HTTP requests performed while saving a map

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7858] opened 2022-02-09 15:02 UTC
## Description

Wen saving a map some strange (probably wrong) HTTP requests are performed.

As soon as you open the _Save_ modal window, the following GetLegendGraphic request is performed (even if it shouldn't ) moreover with a wrong authkey if the user is authenticated:

https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&height=50&width=100&layer=gs%3Aus_states&style=pophade&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels%3Aon&LANGUAGE=en&SCALE=9028&authkey=<authkey-uuid>

After saving the map some other requests to geostore are performed (and  also these ones shouldn't):

https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/resource/32724
https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/resource/23110
https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/resource/32556
https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/resource/24365
https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/resource/32659
https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/resource/34428
https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/resource/32724

Response code is HTTP 404

## How to reproduce

- Reproduced with [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)

*Expected Result*

No wrong (and especially failing) requests are performed while saving a map

*Current Result*

![strange_req.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/99516c35-2667-47f4-8211-937eef0b2792)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This problem seems affecting both DEV and QA

**Comment by DavidQuartz** [comment] 2022-02-24 11:45
@tdipisa I am unable to reproduce the issue. From my tests, opening the Save Modal triggers only 2 (details, and permissions) which seem to be expected. After saving, there are no requests to geostore. And every request throughout my tests have been successful.

Could there be any additional information which may help to reproduce the issue?

Just in case this is important: I first had to do a Save As to be able to do a Save. So the tests have been with my version of the map since I do not have permission to execute a direct Save on the original map.

**Comment by offtherailz** [comment] 2022-02-24 14:52
Hi @DavidQuartz, Did you performed the test on your local machine? 
Maybe this problem affects only dev instance that already contain many maps, dashboards, geostories and contexts.

**Comment by DavidQuartz** [comment] 2022-02-24 14:58
@tdipisa I performed the test on both the dev instance and on my local machine. I've attached a screenshot from the dev instance.

<img width="1920" alt="Screenshot 2022-02-24 at 14 57 35" src="https://user-images.githubusercontent.com/42542676/155548881-af5e8713-5b5e-4c6a-b800-66c7a9a252e3.png">

**Comment by tdipisa** [comment] 2022-02-24 16:39
> @offtherailz I performed the test on both the dev instance and on my local machine. I've attached a gif from the dev instance.
> 
> ![response1](https://user-images.githubusercontent.com/42542676/155549618-9a493889-20aa-42ed-8b22-6bd97298b073.gif)

@DavidQuartz look better the GIF I provided in description. You have to look at _Console_ not _Network_ tab.

**Comment by DavidQuartz** [comment] 2022-02-28 11:06
@tdipisa this bug is caused by the linked resources associated with this map. The GetLegendGraphic requests is triggered by an embedded Legend in the map's details, but since the `authkey` is expired because it was persisted in the past, the request fails and the result is a broken image with an `undefined` alt text.
![Screenshot 2022-02-28 at 09 32 14](https://user-images.githubusercontent.com/42542676/155959084-406427fd-8018-4854-9d23-fee01d8682e2.png)

Also appears to reference other resources which may no longer exist on the server, hence the later requests and their 404 responses. 

My investigations show that this may not be an actual bug but a result of obsolete data associated with this map, persisted by the backend.
Currently this issue may apply to resources which meet similar conditions as this.

**Comment by tdipisa** [comment] 2022-02-28 11:24
@DavidQuartz thank you, I understand. In that case it is not a bug, I agree. Anyway, can you please let me know about the one below?

>Also appears to reference other resources which may no longer exist on the server, hence the later requests and their 404 responses.

Which are the other resources are involved for this map?

**Comment by offtherailz** [comment] 2022-03-02 11:51
I sync with David and, thanks to his investigation results I have found the following:

On every save (from map viewer or the home page), the home page interceptors listen for a change in order to update the result list. (We can optimize it to avoid in certain circumstances, for instance inside the map, but it will happen anyway if you save the resource attributes from the home page). 

The undesired requests are caused by the system that handles the maps saved within contexts.  For each map of this kind, the home page need to load also the context attributes (not the body) in order to: 
- Guess if the context still exists and it is accessible for the user (otherwise it will use the default context).
- Get the "contextName", needed to generate the link for the user, when he clicks on the map. (the path is /context/{contextName}/{mapId})

The request failures are due to some maps that has been saved with a context, but later the context has been deleted. 
To avoid this, we proposed some solution with this [issue](https://github.com/geosolutions-it/MapStore2/issues/5149) but maybe we can design something different at nowdays. 

So apparently this is not a bug itself, but a the consequence of a known issue. So for me is closed. We can remove the maps or recreate them if needed. (please @DavidQuartz report the maps that have this problem). 

About the re-design of #5149 I suggest to replace the "create map within a context", instead associating the map to a default context.
This has the advantage of being : 
 - Editable
 - Easier to understand
 - Somehow from the UI we can allow to open the map in another context, to make the editing of the map easier)

**Comment by DavidQuartz** [comment] 2022-03-02 12:00
@tdipisa @offtherailz the maps current having this problem are this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/32564) and this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/32796)

**Comment by offtherailz** [comment] 2022-03-04 08:39
I deleted them because they was both made to live within a context. the contexs has been removed, so no need for them anymore.

**Comment by offtherailz** [comment] 2022-03-08 09:01
Closed in favor of https://github.com/geosolutions-it/MapStore2/issues/7917 and https://github.com/geosolutions-it/MapStore2/issues/5149

**Closed by offtherailz** 2022-03-08 09:01 UTC
Labels: bug, Priority: High, Internal
