### ISSUE TITLE
Problem after the logout on new geostory 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5517] opened 2020-06-19 16:07 UTC
## Description

If you logout after clicking Leave, the blank page appears.

![error](https://user-images.githubusercontent.com/56537133/85143213-c672f200-b249-11ea-86a1-3b9364660e74.gif)
## How to reproduce

-  Open new story
- Edit something
- Click on logout
- Click on Leave

*Expected Result*

You are redirected to the home page

*Current Result*

A blank page appears

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment] 2020-06-22 16:16
@offtherailz Logout a new story, the Login panel opens but, as happens on Maps and Dashboard, you should be redirected to the home page.
![error](https://user-images.githubusercontent.com/56537133/85310614-84011d80-b4b4-11ea-91fa-f4df2e76d6cd.gif)

**Comment by offtherailz** [comment] 2020-06-23 08:41
@ElenaGallo . I simply restored how it was working before, because I noticed a regression. Dashboard do not redirect too (it prompts the login). Only map redirects. 
Uniforming the 3 systems is a good proposal, but I didn't wanted to refactor at this stage, so I only fixed what was broken.

**Comment by tdipisa** [comment] 2020-06-23 09:14
@offtherailz I agree, @ElenaGallo please open a new issue for 2020.02.01 milestone and let's close this one if all is working fine for now.

**Closed** 2020-06-23 09:26 UTC
Labels: Accepted, GeoStory, Priority: Blocker, bug
