### ISSUE TITLE
 Layer crs bounds different from EPSG:4326 trigger warning message on projection compatibility

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#4237] opened 2019-09-20 16:42 UTC
### Description
This issue can be verified in GeoNode MapStore client and is due to wrong control in MapStore for projection compatibility.

see here for more details:
- https://github.com/geosolutions-it/geonode/issues/366#issuecomment-533023941
- https://github.com/GeoNode/geonode-mapstore-client/issues/23#issue-495658431

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- all not related to browsers

*Steps to reproduce*

- create a layer with a bbox in EPSG:3857 but compatible with the projection
- save the map
- refresh map

*Expected Result*

- If the layer is compatible with map the warning notification should not be visible even if the bbox is in a crs different from EPSG:4326

*Current Result*

- this message shows up
![Selection_026](https://user-images.githubusercontent.com/43670920/65149379-456c9d00-da22-11e9-91af-a065cafe5a79.png)

### Other useful information (optional):
see also #4425

**Comment by tdipisa** [comment] 2019-11-14 16:37
Duplicate of #4425

**Closed by tdipisa** 2019-11-14 16:37 UTC
Labels: CRS Selector, Priority: Medium, bug
