### ISSUE TITLE
Incorrect connection of the parent table with the map and another widget

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9739] opened 2023-11-23 12:07 UTC
## Description

As reported in the User Guide [here](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/connecting-widgets/#connecting-table-widgets-with-other-widgets), if the widget has been created on the same dataset (layer) of the Parent Table then two filters will be applied in AND to the widget itself: the spatial filter of the Map widget and the attribute filter defined in the Parent Table.

At this moment this type of connection is not correct. The chart widget is connected to the map but not to the Parent Table.

## How to reproduce

-  Open [this dashnoard](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/47329)
-  Write "Florida"  to `STATE_NAME` quick filter

*Expected Result*

https://github.com/geosolutions-it/MapStore2/assets/56537133/60f4bfd2-e59a-470d-88e0-a7be5160aac0

*Current Result*

https://github.com/geosolutions-it/MapStore2/assets/56537133/00425c7e-77b5-4322-a7da-2367bad93ca3

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment] 2023-11-27 17:54
there is problem with the introduction of traces and propagation of dependencies, I've spotted a problem here

![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/0fe598dc-e293-4aa4-b622-f27edc7ff78d)

in particular the fetch of table deps from a trace

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/selectors/widgets.js#L113

i suppose it is enough to properly fix this selector, but i had no time to check it.
if it this the case it should be a quick fix otherwise it may take some more effort

**Comment by tdipisa** [comment] 2023-11-28 09:23
This is a regression imho since it seems affecting also QA. @MV88 @ElenaGallo please confirm.

**Comment by MV88** [comment] 2023-11-28 09:41
yeah,  it has been introduced with multivariable charts work

**Comment by tdipisa** [comment] 2023-11-28 09:53
@MV88 
>yeah, it has been introduced with multivariable charts work

it is not possible since that work is not present in QA but only in DEV, therefore I think the source of the problem is another. Anyway let's check what introduce this regression @dsuren1.

**Comment by MV88** [comment] 2023-11-28 10:04
ok, anyway there it fails because it does not find the editing layer in the charts, dues to the introduction of traces.

**Comment by dsuren1** [comment] 2023-11-30 09:10
### Investigation
The regression was introduced in `2021.02.00` by #7376 in [buildDependencies](https://github.com/geosolutions-it/MapStore2/pull/7414/files#diff-94f398bd89a29cb576f5b698a82647dcf4c50f9a6cff82b3fc7c10e90306ddfeR72) function stop from building a correct dependency recursively. 

Removing the condition of `!ret.mapSync` from `buildDependencies` allows us to propogate the dependency properly and fixes this issue. But it reintroduces the `Maximum call stack size exceeded` exception, so we need to find a better way to both the scenarios

**Comment by tdipisa** [comment] 2023-11-30 09:35
@dsuren1 should we review pts assigned to this issue ?

**Comment by dsuren1** [comment] 2023-11-30 09:49
Yes @tdipisa, maybe a point more. As we need to find a common ground to fix both issues without breaking new changes. Furthermore the investigation took some time too.

**Closed** 2024-01-15 15:34 UTC
Labels: bug, Internal, Dashboard, Widgets, BackportNeeded, Regression, Charts
