### ISSUE TITLE
Sometime saving a geostory after adding a thumbnail for items on GeoCarousel causes an error

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7610] opened 2021-11-29 17:29 UTC
## Description

Sometime saving a geostory after adding a thumbnail for items on GeoCarousel causes an error

## How to reproduce

-  Open [this geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/35589)
- Scroll on geocarousel section 
- Follows the steps on the gif below:

![save error](https://user-images.githubusercontent.com/56537133/143914487-d9236bd7-a15d-4450-b393-61b9db6073a1.gif)
 

*Expected Result*

It is possible to save the geostory 
*Current Result*

A 500 Internal error server appears.

> PUT https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/data/35589 500 (500)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment] 2021-12-09 17:15
The problem seems DB side
![image](https://user-images.githubusercontent.com/1280027/145444069-f965d0c0-dc8e-4214-b546-b8cf61255ca0.png)

@offtherailz please fix it. Thank you.

**Comment by offtherailz** [comment] 2021-12-09 17:23
I did a fix to column size on prod DB. Now I executed the same commands in dev instance.

**Comment by dsuren1** [comment] 2021-12-15 10:35
@ElenaGallo I believe the fix made by @offtherailz in DEV instance has fixed this issue. I'm not able to reproduce it. So, could you please confirm? Thanks!

**Comment by tdipisa** [comment] 2021-12-15 10:37
@dsuren1 I think the issue affects also QA. @offtherailz please provide feedback

**Comment by dsuren1** [comment] 2021-12-15 10:46
Works fine in QA too

**Comment by offtherailz** [comment] 2021-12-15 11:00
Great, so we can close it.

**Comment by tdipisa** [comment] 2021-12-15 11:01
@offtherailz did you checked this?

**Comment by offtherailz** [comment] 2021-12-15 11:07
The migration script and the annotation report the same number: 

https://github.com/geosolutions-it/geostore/blob/520d408d95cc23568841b43409c0e459b5164185/src/core/model/src/main/java/it/geosolutions/geostore/core/model/StoredData.java#L63

`10000000`

https://github.com/geosolutions-it/geostore/blob/520d408d95cc23568841b43409c0e459b5164185/doc/sql/migration/postgresql/postgresql-migration-from-v1.2-to-v1.4.2.sql#L13

**Comment by tdipisa** [comment] 2021-12-15 11:10
Good @offtherailz. I'm going to close then. Thank you.

**Closed by tdipisa** 2021-12-15 11:10 UTC
Labels: bug, Priority: Blocker, GeoStory
