### ISSUE TITLE
Custom colors are not applied in the widget 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8679] opened 2022-10-11 09:46 UTC
Custom colors are not applied in the Bar and Pie Chart widget (they are visible only in preview)

![widget.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/adfcb17c-bf0d-4e89-9b80-b7c6d73f9133)

**How to Reproduce**
- Open [this dash](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/41760)
- Click on Edit from Widget card

*Current Result*
The Custom colors are not applied in the Bar Chart

**Comment by tdipisa** [comment] 2022-10-11 11:03
@alex-fko we found this problem in DEV (QA is working as expected). We need a quick check to understand what has introduced the regression.

**Comment by tdipisa** [comment] 2022-10-11 12:17
@alex-fko also other dashboards used for demo seems to be affected by the same problem: https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/21694

**Comment by alex-fko** [comment] 2022-10-14 07:50
@ElenaGallo @tdipisa It was caused by not passing a property holding information about classification configuration down to the component that renders chart. It should be fixed by the changes in #8688

**Closed** 2022-10-21 15:58 UTC
Labels: bug, investigation, Priority: High, Accepted, Widgets, Regression, C040-COMUNE_GE-2022-CUSTOM-SUPPORT
