### ISSUE TITLE
Printing a annotation (Polygon) with modified vertices throws an exception

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9319] opened 2023-08-02 11:28 UTC
## Description
When printing a polygon annotation which vertices modified either by deleting or changing the vertices position, an incomplete polygon geometry is formed. Trying to print an annotation containing this malformed geometry results in the following exception

```java
Error on printing: Error while generating PDF: java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
```

## Acceptance criteria
- [x] Polygon annotation should be printable when vertices are modified (delete or moving position)
- [x] Import annotation with malformed annotation that previously exported should be printable (For backward compatibility)

## How to reproduce
- Create an annotation with polygon geometry
- Save the annotation
- Modify the annotation's polygon geometry by moving the positions of the coordinates or by deleting a coordinate (possible 
 when > 3)
- Save the geometry and annotation
- Try printing the annotation to observe the error

*Expected Result*
Should be able to print annotation with all types of geometries

*Actual Result*
![annotations_bug](https://user-images.githubusercontent.com/1280027/215730756-32093cd6-6f33-4e44-bffc-ff8311fe030d.gif)

- [x] Not browser related

## Other useful information
Ref: 
https://github.com/georchestra/mapstore2-georchestra/issues/617
https://github.com/geosolutions-it/MapStore2/issues/7780

**Comment by tdipisa** [comment] 2023-08-02 15:05
@dsuren1 thank you 
I would like to review this issue on the light of what we are doing for https://github.com/geosolutions-it/MapStore2/issues/9094

**Comment by tdipisa** [comment] 2023-08-02 16:06
@dsuren1 after talking with @allyoucanmap I can confirm that it is better to wait for #9094 (including review and tests) before starting the development of this issue since #9094 introduces consistent refactor for the annotation tool.

**Comment by tdipisa** [comment] 2023-08-30 13:29
@dsuren1 the work in progress for #9094 will be part of 2024.01 (the plan is changed for this). The stable branch for 2023.02.xx has already been created, therefore you can contribute the fix for this issue directly there.

**Closed** 2023-09-22 13:38 UTC
Labels: bug, BackportNeeded, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 3
