### ISSUE TITLE
Printing fails for some maps on Chrome

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#843] opened 2016-07-12 15:32 UTC
As per the subject check printing on [this](http://mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/464?_k=lm66i2) map.

**Comment by mbarto** [comment] 2016-07-12 15:37
That map is served by a GWC only service, so can only work in tiled mode, while MapFish can only work in untiled mode currently with WMS, so requests from MapFish to GWC fail because of width and height not being 256. This can only be fixed implementing tiled mode for WMS in MapFish.

**Comment by simboss** [comment] 2016-07-13 05:39
We should then open an issue (about letting use know that the print failed for a reason) as well as an enhancement ( to implement support for tiled prints).

See #846 and #847.

**Comment by tdipisa** [comment] 2018-07-27 15:49
Duplicate of #846

**Closed by tdipisa** 2018-07-27 15:49 UTC
Labels: LeafLetJS, Manual Test Required, OL3, Priority: Blocker, bug, duplicate
