### ISSUE TITLE
Carousel text is not easy to read in the new home

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#937] opened 2016-08-31 16:56 UTC
Because of new font and colors.
![image](https://cloud.githubusercontent.com/assets/1279510/18138316/6da6cf2c-6fac-11e6-888b-0aa5d19f074a.png)

Maybe also the text on top has too much margin, at list on mobile:

![image](https://cloud.githubusercontent.com/assets/1279510/18138366/9e1cedda-6fac-11e6-9bb9-8e926447a964.png)

**Comment by mbarto** [comment] 2016-09-09 10:54
Fixed with https://github.com/geosolutions-it/MapStore2/pull/957

**Comment by offtherailz** [comment] 2016-09-09 12:35
Does this solution fit for you ? 
![image](https://cloud.githubusercontent.com/assets/1279510/18387059/9a9a0450-769a-11e6-92fb-bb9652f5578b.png)

**Comment by mbarto** [comment] 2016-09-09 12:51
Good for me

**Comment by tdipisa** [comment] 2016-09-09 12:55
+1




*==GeoServer Professional Services from the
experts!Visit http://goo.gl/it488V <http://goo.gl/it488V> for more
information.==*

Dott. Ing. Tobia Di Pisa
Software Engineer

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 333 8128928 <%2B39%20%20333%208128928>

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------
Call
Send SMS
Add to Skype
You'll need Skype CreditFree via Skype
-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

2016-09-09 14:35 GMT+02:00 Lorenzo Natali <notifications@github.com>:

**Closed** 2016-09-09 14:02 UTC
Labels: bug, pending review
