### ISSUE TITLE
Problem while printing measurements as a layer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5178] opened 2020-04-23 15:56 UTC
## Description

If you convert some measurements in a layer and then you try to print, there is an error reported by the print backend

## How to reproduce

-  Add some measurements in the map
- Covert them in a layer in TOC
- Print the map

*Expected Result*

The map is correclty printed

*Current Result*

The following error occurs

![image](https://user-images.githubusercontent.com/1280027/80120673-a39ac900-858b-11ea-8ebc-31a4b1a5bbe1.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment] 2020-05-06 10:42
@mbarto When the map is saved with measurements as a level, this printing problem still occurs.

*How to reproduce* 
- Add some measurements in the map
- Covert them in a layer in TOC
- Save the map
- Print the map

**Comment by tdipisa** [comment] 2020-05-06 11:51
@ElenaGallo for me it is working. Please try to clean up the cache and reload

**Comment by mbarto** [comment] 2020-05-06 12:22
@ElenaGallo I will check, it could be, because the behaviour is based on a layer attribute that is probably not saved

**Comment by tdipisa** [comment] 2020-05-06 12:36
@mbarto I've checked it again, and it seems that there is a strange behavior here indeed.

I've created [this map ](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/24726) where the printing was working initially.

Then I've opened the same map using QA and the print fails with the error above.

Then I've re-opened themap in DEV and the printing is failing now in DEV too.

The [map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/24719) shared by @ElenaGallo and used for her tests, was not working for me at all.

I have also to mention a regression that I've identified during the second test: the line curve isn't maintained now in DEV while printing a length measurement. In QA we have the following:

![image](https://user-images.githubusercontent.com/1280027/81177181-8cee6c00-8fa6-11ea-8a29-acdd539d77d6.png)

But in DEV we have the following situation:

![image](https://user-images.githubusercontent.com/1280027/81177360-ce7f1700-8fa6-11ea-9b06-154f52c18dcd.png)

I don't know if it depends by the something in the @vlt1 implementation or not. Can you please check @mbarto and let me know if we need to involve @vlt1 in the fix?

**Comment by mbarto** [comment] 2020-05-06 14:36
@tdipisa about curved lines I have no idea, I am going to fix the print for saved maps

**Comment by mbarto** [comment] 2020-05-06 14:51
made a new PR with a more "solid" fix, hopefully

**Comment by offtherailz** [comment] 2020-05-07 07:45
ok, you used name, so this property is saved. The only problem that I see with this solution is that old saved maps with measurements will still have problems while new saved maps will work, right @mbarto ?
If so, and if it is acceptable @tdipisa , you should take it into account for testing. 

So @ElenaGallo , if mauro and Tobia confirm, take into account that to make it work you have to save a new map, the old map will still not work.

**Comment by mbarto** [comment] 2020-05-07 08:13
@offtherailz @tdipisa the problem is that there is a lot of hardcoded stuff involved, so we should refactor vector layers ASAP to use only one way of styling them, not one for annotations / measurements and one for all the rest (without a reliable way to know which one is used). This is where these kind of problems come from.
One day we should just stop the engines and refuel the car properly before we find ourselves stuck in the middle of nothing (with no phone connection)

**Comment by tdipisa** [comment] 2020-05-07 08:31
@ElenaGallo please proceed and close if it is working good

**Comment by ElenaGallo** [comment] 2020-05-08 16:48
@tdipisa if the problem of curved lines is not an issue of this PR, I can proceed with closing the issue.

**Comment by tdipisa** [comment] 2020-05-11 07:27
@ElenaGallo, @vlt1 has provided a fix for the geodesic line in [this PR](https://github.com/geosolutions-it/MapStore2/pull/5247). Therefore, this issue can be closed if the other tests have passed.

**Closed** 2020-05-13 14:42 UTC
Labels: Accepted, Priority: High, bug, geOrchestra
