### ISSUE TITLE
It is not possible to save WMS or WMTS services with Catalog plugin

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3896] opened 2019-07-02 13:57 UTC
### Description
TOC and MetadataExplorer (Catalog ) plugins use the same `/epics/catalog` with different API argunment, this behaviour causes an override when MetadataExplorer is imported in plugin.js before TOC plugin.
The overridden epics work for TOC but not for MetadataExplorer because some services are missing (`wms`, `wmts`)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all browser , not related to browser

*Steps to reproduce*

- open a map
- open catalog
- click on edit (pencil button)
- add current wms service url: `https://gs-stable.geo-solutions.it/geoserver/wms`, type: `wms`, title: `GeoSolutions GeoServer WMS`
- click on save

*Expected Result*

- catalog is saved correctly

*Current Result*

- nothing happens and error in console

**Comment by tdipisa** [comment] 2019-07-02 14:11
@allyoucanmap it seems a duplicate of #3894. If this is the case, please comment #3896 and clode this issue adding a **duplicate** label.

**Closed** 2019-07-02 14:21 UTC
Labels: Priority: Blocker, bug
