### ISSUE TITLE
Additional marker/icon symbolizers are misplaced in 3D view

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9431] opened 2023-09-12 16:36 UTC
## Description

Found in https://github.com/geosolutions-it/MapStore2/pull/9397#pullrequestreview-1621872964

The additional marker and icon symbolizer are not correctly displaced because of the use of `billboard.eyeOffset` property (eg. as polyline start/end points). We introduced the `eyeOffset` property as a way to order multiple billboard applied to the same feature. Inside this comment https://github.com/geosolutions-it/MapStore2/issues/9362#issuecomment-1710436888 there are other information about the use of [eyeOffset](https://github.com/geosolutions-it/MapStore2/blob/3e3f3ffe33c64f8a41412f85876adeafbc7bd2b3/web/client/utils/styleparser/CesiumStyleParser.js#L604) including a link to a Cesium issue still open about to introduce the possibility to add a zIndex to entities.

We need to investigate and understand if it possible to replace eyeOffset or completely remove it because it seems it causing more problems rather than benefits

## How to reproduce

https://github.com/geosolutions-it/MapStore2/assets/19175505/9cf9798c-aa67-48a2-a5e1-f49ffc187030

- create an line annotation in 3D on top of 3D feature
- add a style icon to the annotation line as starting point

*Expected Result*

The icon is visible at the correct location
![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/3502218c-b281-48d1-8a8b-4f11499d0774)

*Current Result*

![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/2897f33d-2a1a-4699-8d37-0411e94fc6cc)

The icon is misplaced behind the feature

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment] 2024-01-11 07:55
@tdipisa
Unable to reproduce this issue anymore probably changes made as part of #9807 handled this case.
<img width="1257" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/be6020aa-e6e8-4c2f-919a-a7a782def552">

@allyoucanmap Kindly confirm. Thanks!

**Comment by allyoucanmap** [comment] 2024-01-11 14:46
@dsuren1 yes, probably in that refactor for extrusion I removed completely the eyeOffset

**Comment by tdipisa** [comment] 2024-01-11 14:58
Thank you @dsuren1 and @allyoucanmap. Moving to test to verify again also with @ElenaGallo

**Closed** 2024-01-18 10:50 UTC
Labels: bug, investigation, Accepted, 3D, C027-COMUNE_FI-2023-SUPPORT
