### ISSUE TITLE
Identify maxItems cfg option removed

### ISSUE THREAD

**Issue by pgssimon** [geosolutions-it/MapStore2#4238] opened 2019-09-23 00:40 UTC
### Description
Hi
In one of my localConfig.json I have set maxItems for the Identify plugin

            {
                "name": "Identify",
                "cfg": {
                    "showHighlightFeatureButton": true,
                    "draggable": false,
                    "dock": true,
                    "viewerOptions": {
                      "container": "{context.ReactSwipe}"
                    },
                    "maxItems": 200
                },
                "override": {
                    "Toolbar": {
                        "position": 11
                    }
                }
            },

However this cfg setting is no longer available, is there a replacement setting that I have missed?

Was removed at this commit...

https://github.com/geosolutions-it/MapStore2/commit/e68ce42ca1ad311767ec229ba8afcab83ce13e2b#diff-cb0e46ea9c7290f7a328445a8d05f9d7

This is very important as we are not able to display the correct number of records, for instance in the screenshot below there should be 39 Building Consents...
 
![wairoa_identify_error_no_records_displayed](https://user-images.githubusercontent.com/40550145/65396876-3c534580-ddff-11e9-8d39-b1225580009e.png)

Cheers
Si

**Comment by mbarto** [comment] 2019-09-24 15:39
@pgssimon you are right, it's a regression
@offtherailz we could probably move the missing identify options that were in the plugin config in the mapInfo state, so that they can be overridden by localConfig.json

**Comment by offtherailz** [comment] 2019-09-27 16:41
The options originally was get from the graphic component properties.
After the refactoring maps the `options` with this selector. 
https://github.com/geosolutions-it/MapStore2/blob/b812406506b62d3f4ea78783acb0978f11e9db67/web/client/selectors/mapInfo.js#L83-L88

A couple of changes like the followings should restore the possibility to customize maxItems : 

const showMarkerSelector = state => state && state.mapInfo && state.mapInfo.showMarker
```diff
const identifyOptionsSelector = createStructuredSelector({
        format: generalInfoFormatSelector,
        map: mapSelector,
        point: clickPointSelector,
        currentLocale: currentLocaleSelector,
+       maxSize: (state) => get(state, "mapInfo.configuration.maxSize", 10);
    });
```

```diff
"mapInfo": {
    "enabled": true, // enabled by default
    "disabledAlwaysOn": false, // if true, disable always on setup
    "configuration": {
      "showEmptyMessageGFI": false // allow or deny the visiibility of message when you have no results from identify request
      "infoFormat": "text/plain" // default infoformat value, other values are "text/html" for text only or "application/json" for properties,
+     "maxSize": 50
    }
  }
```

This proposed solution supports again to `maxItems` (even "params" should work) from the state, editing it as documented here [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Identify.jsx#L143)

**Comment by pgssimon** [comment] 2019-09-29 19:21
@offtherailz that would be perfect

**Comment by myrdstom** [comment] 2020-10-21 03:50
This Github issue has a code suggestion which I have implemented. I am however unsure how exactly to recreate and test it out. Any assistance would be appreciated

**Comment by MV88** [comment] 2020-10-21 08:19
Hi @pgssimon I recently tested in DEV and was able to fetch 67 items in a layer

so i am wondering if this issue is still valid

May you double check it?

**Comment by MV88** [comment] 2020-10-21 08:56
closing since we can no longer reproduce it

**Comment by MV88** [comment] 2020-10-21 09:03
We would like to reintroduce the maxItems aswell

**Comment by pgssimon** [comment] 2020-10-21 22:23
I am currently setting up a new server with MapStore 2020.02.01 will check against that

**Closed** 2020-10-26 09:01 UTC
Labels: Accepted, Good first issue, Priority: Medium, user feedback
