### ISSUE TITLE
Annotation makes hangup mapfishprint

### ISSUE THREAD

**Issue by MaelREBOUX** [geosolutions-it/MapStore2#7780] opened 2022-01-26 13:01 UTC
## Description

When trying to print an annotation, we get a Java error from (we guess) Mapfisprint.

```
Error on printing: Error while generating PDF: java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring at
 org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:90) at
 org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:85) at
 org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:356) at
 org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:343) at
 org.mapfish.geo.MfGeoJSONReader.decodePolygon(MfGeoJSONReader.java:151) at
 org.mapfish.geo.MfGeoJSONReader.decodeJtsGeometry(MfGeoJSONReader.java:117) at
 org.mapfish.geo.MfGeoJSONReader.decodeGeometry(MfGeoJSONReader.java:88) at
 org.mapfish.geo.MfGeoJSONReader.decodeFeature(MfGeoJSONReader.java:84) at
 org.mapfish.geo.MfGeoJSONReader.decodeFeatureCollection(MfGeoJSONReader.java:75) at
 org.mapfish.geo.MfGeoJSONReader.decode(MfGeoJSONReader.java:63) at
 org.mapfish.print.map.readers.VectorMapReader.<init>(VectorMapReader.java:75) at
 org.mapfish.print.map.readers.VectorMapReader$Factory.create(VectorMapReader.java:57) at
 org.mapfish.print.map.readers.MapReaderFactoryFinder.create(MapReaderFactoryFinder.java:39) at
 org.mapfish.print.map.MapChunkDrawer.renderMap(MapChunkDrawer.java:142) at
 org.mapfish.print.map.MapChunkDrawer.renderImpl(MapChunkDrawer.java:87) at
 org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55) at
 org.mapfish.print.config.layout.MapBlock$1.render(MapBlock.java:68) at
 org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183) at
 org.mapfish.print.config.layout.MapBlock.render(MapBlock.java:64) at
 org.mapfish.print.config.layout.Page.render(Page.java:80) at
 org.mapfish.print.config.layout.Layout.render(Layout.java:67) at
 org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30) at
 org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:62) at
 org.mapfish.print.MapPrinter.print(MapPrinter.java:184) at
 org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:409) at
 org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:190) at
 org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:107) at
 javax.servlet.http.HttpServlet.service(HttpServlet.java:650) at
 javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at
 org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at
 org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) at
 org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) at
 org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494) at
 org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at
 org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104) at
 org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025) at
 org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at
 org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) at
 org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137) at
 org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) at
 org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2512) at
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at
 org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at
 java.lang.Thread.run(Thread.java:748) 
```

## How to reproduce

- Load this annotation.
- Zoom on it
- print the map

[Annotations.zip](https://github.com/geosolutions-it/MapStore2/files/7941861/Annotations.zip)

## Expected Result

a PDF with the annotation

## Current Result

Error while printing

## Other useful information

- [x] Not browser related

- MapStore geOrchestra 1.2.x
- MapStore 2021.02.xx (c87f5fa9)

![image](https://user-images.githubusercontent.com/6370443/151167125-27d6f852-e389-4705-8cad-c657d7d6d66f.png)

**Comment by MaelREBOUX** [comment] 2022-01-31 13:53
I précise that the geometry is good (from FME full Geometry Validator test suite).

**Comment by MaelREBOUX** [comment] 2022-05-23 08:45
Hello @tdipisa 

Here another annotations print problem. 

[Annotations.zip](https://github.com/geosolutions-it/MapStore2/files/8752866/Annotations.zip)

**Comment by MaelREBOUX** [comment] 2022-05-23 08:48
I can reproduced on the up-to-date https://georchestra.geo-solutions.it/

**Comment by landryb** [comment] 2022-05-23 08:52
at first, drawing simple polygons i couldn't reproduce the issue on https://georchestra.geo-solutions.it/mapstore/#/, but importing the annotations.json export from @MaelREBOUX 's comment yes it also fails to validate here with the same error message.

To me the traceback shows that geotools fails to validate the geometry (that was created directly in ms2 annotation tools, from my understanding)

**Comment by landryb** [comment] 2022-05-23 09:01
@tdipisa : live-debugging with @MaelREBOUX we've found how to make it generate a geometry that fails to print:
- draw a polygon
- double-click at the end to 'finish' the polygon -> that generates a duplicate edge at the same coordinates
- in the list of edges, remove the last duplicate edge, save the annotation
- this geometry will fail to validate & print

**Comment by landryb** [comment] 2022-05-23 09:05
![Peek 23-05-2022 11-03](https://user-images.githubusercontent.com/3421760/169784478-3c005a15-7c0d-4508-90f6-4b80596f85cc.gif)

**Comment by MaelREBOUX** [comment] 2022-05-23 09:26
I don't know how / why but after removing the 5th vertex : the red point that indicates the end of the polygon / construction is now affected to the the 3rd vertex :

![image](https://user-images.githubusercontent.com/6370443/169788422-f41b1bc0-fb7d-4312-969d-984a6639acf4.png)

But I do not know if it is the source of the problem.

**Comment by MaelREBOUX** [comment] 2022-05-23 12:20
Well. I think we have an issue. As you modify a previous polygon (which was printable) : you ever get a print error.

![ms2_print_annotation_bug](https://user-images.githubusercontent.com/6370443/169817692-49d1fe7e-39ff-4dfd-b588-d798eb526949.gif)

**Comment by MaelREBOUX** [comment] 2022-05-23 12:47
It does not affect the lines. Only polygons.

![ms2_print_annotation_bug_line](https://user-images.githubusercontent.com/6370443/169822326-ff743c61-8cf2-43ce-ab50-c73a99146f62.gif)


MapStore2-geOrchestra | :2022.01.xx(9c08c926)
MapStore2 | :2022.01.xx(e9b4af71)

on https://georchestra.geo-solutions.it/mapstore/#/

**Comment by MaelREBOUX** [comment] 2022-05-23 13:51
OK précision : it happens only if you delete a vertex o_O Nothing happens if you move a vertex.

**Comment by MaelREBOUX** [comment] 2022-11-18 13:54
Hello @tdipisa no investiguation yet ?

**Comment by tdipisa** [comment] 2022-11-21 11:30
Hi @MaelREBOUX we haven't had a chance to investigate it yet.

**Comment by MaelREBOUX** [comment] 2023-01-17 17:17
Problem is still present on these versions :
- MapStore2-geOrchestra : 2022.02.00-geOrchestra (f3ce6b9e)
- MapStore2 : 2022.02.xx (15c07932)

**Comment by tdipisa** [comment] 2023-01-31 10:09
This has been reproduced on both MS DEV and QA

![annotations_bug](https://user-images.githubusercontent.com/1280027/215730756-32093cd6-6f33-4e44-bffc-ff8311fe030d.gif)

**Comment by dsuren1** [comment] 2023-08-02 11:33
Closing this issue in favour of https://github.com/geosolutions-it/MapStore2/issues/9319

**Closed by dsuren1** 2023-08-02 11:33 UTC
Labels: bug, C169-Rennes-Métropole-2023-GeOrchestra4
