### ISSUE TITLE
Widgets - legend scroll does not work properly when height is too low

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#9615] opened 2023-10-17 14:01 UTC
## Description

try to use this dashboard 

[pie legend issue-dashboard.json](https://github.com/geosolutions-it/MapStore2/files/12929433/pie.legend.issue-dashboard.json)

## How to reproduce

- import the previous dashboard
- scroll from top to bottom

*Expected Result*

scroll goes down and you can see the correct list of items

*Current Result*

scroll goes to the end skipping some legend items

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

it appears the issue in on d3.event.deltaY value which is 100 
and the result of legendObj._scrollY +
`((d3.event.deltaY / scrollBarYMax) * scrollBoxYMax)`

is 847 which makes the scrollbar to move to the end because `scrollBoxYMax` becomes equal to `scrollBoxY`
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/89aeff2f-ccc1-486f-a895-cf1e359752ca)

![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/0b1aaf62-d3d9-4ea2-80d8-ded53ecdbf7b)

**Comment by tdipisa** [comment] 2024-05-20 09:00
@dsuren1 is this one connected somehow with #10070?

**Comment by dsuren1** [comment] 2024-05-20 10:26
@MV88 @tdipisa 
Could you please try it in DEV. Recreated a similar widget (as the one attached doesn't load for me) and I'm able to scroll it fine.

https://github.com/geosolutions-it/MapStore2/assets/26929983/c4984f61-9930-42a7-8da5-1da0b1a73435

**Comment by tdipisa** [comment] 2024-05-20 11:16
Confirmed also by @MV88. That's a duplicate of #10070

**Closed by tdipisa** 2024-05-20 11:16 UTC
Labels: bug, C027-COMUNE_FI-2023-SUPPORT
