### ISSUE TITLE
Timeline does not set the slider on correct position 

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8347] opened 2022-06-20 15:50 UTC
## How to reproduce

-  login and create a new map
- import this map
[timeline-new-map.zip](https://github.com/geosolutions-it/MapStore2/files/8941985/timeline-new-map.zip)
- open the timeslider

*Expected Result*

In previous version of mapstore at the first import of a layer with time dimension the cursor was positioned to the latest available date/time.

Here GeoNode 3.3.x where the behaviour was still the old one, the submodule is updated to this commit https://github.com/geosolutions-it/MapStore2/tree/faee07b04ca5b475f2241b58fe48e59ab246de0b

![image](https://user-images.githubusercontent.com/19175505/174638770-4ad7f9aa-8e07-4739-8472-e439ccfe3c9c.png)

*Current Result*

the cursor is missing

![image](https://user-images.githubusercontent.com/19175505/174638286-8b0824fc-027b-4a81-be27-47d43bf5bb57.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment] 2022-06-23 13:05
@dsuren1 I need first of all an investigation to understand if this issue is a regression or not included after recent updates we provided for the timeline (eg. https://github.com/geosolutions-it/MapStore2/issues/7958).

**Comment by dsuren1** [comment] 2022-06-28 06:39
@ale-cristofori 
Is this intentional [INIT_TIMELINE](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/reducers/timeline.js#L132), because it replaces the other default `settings` props of `timeline` here mainly `autoSelect: true`, which fails to set the first layer as selected when present in this epics [syncTimelineGuideLayer](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/timeline.js#L234), further failing to set current time in `dimension.currentTime`

Due to this the customTimeKeys are not added causing the timeslider vertical bar element (cursor in timeslider) missing from the time component.

**Comment by ale-cristofori** [comment] 2022-06-28 09:56
@dsuren1, no, it looks like I forgot to include the property, as well as `collapsed`. I got confused by using the `set` function, I thought it merged the state but it actually does not.

@dsuren1 just for curiosity, what's the advantage of using `set()` over the  spread notation ? `. . .state.settings, endValuesSupport, autoSelect, ...`

**Comment by dsuren1** [comment] 2022-06-28 10:28
> @dsuren1 just for curiosity, what's the advantage of using `set()` over the spread notation ? `. . .state.settings, endValuesSupport, autoSelect, ...`

As you know both serves different purpose. Wrt object, Lodash's set allows modification of object and return the modified object while spread let you make a copy of the object.
One advantage when it comes to _code style_ is that `set()` greatly simplies the modification of the **nested** object based on the path  while achieving the same with `spread` on nested object is not so elegant to look at.

> @dsuren1, no, it looks like I forgot to include the property, as well as collapsed. I got confused by using the set function, I thought it merged the state but it actually does not.

spread can be used in set()
Ex: 
```
set(`settings`, {
            ...state.settings,
            showHiddenLayers: action.showHiddenLayers,
            expandLimit: action.expandLimit,
            snapType: action.snapType,
            endValuesSupport: endValuesSupport !== undefined ? endValuesSupport : action.endValuesSupport,
            snapRadioButtonEnabled: snapRadioButtonEnabled !== undefined ? snapRadioButtonEnabled : action.snapRadioButtonEnabled
        }, state)
```

**Closed** 2022-07-06 13:45 UTC
Labels: bug, investigation, Priority: High, Accepted, Internal
