### ISSUE TITLE
Issue in chart creation from feature grid.

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9147] opened 2023-05-08 15:16 UTC
## Description

Trying to create the charts from the feature grid, the builder stops working when you try to select something.

[chart_error.webm](https://user-images.githubusercontent.com/1279510/236862067-9ae157b1-20a4-4460-8a3a-01d03802ef03.webm)

## How to reproduce
-  Open the feature grid for a layer
- click on chart button in the feature grid toolbar
- start selecting attributes or chart types

*Expected Result*

- I'm able to complete the chart creation

*Current Result*

- Selection of attributes or other parts do not work

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment] 2023-06-07 08:35
duplicate of #9202?

**Comment by tdipisa** [comment] 2023-06-09 12:31
@allyoucanmap is this effectively a duplicate? If yes we can close #9202 in favor of this.

**Closed** 2023-06-09 14:02 UTC
Labels: bug, investigation, Regression
