### ISSUE TITLE
Text rule inside the Style editor in visual mode freezes the page 

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6899] opened 2021-05-24 13:41 UTC
## Description
When a TextSymbolizer rule is set inside inside the Style Editor in visual mode, the page freezes. No other action is possible except closing the browser page.

## How to reproduce
- Add a Text rule to a style
- Save the style
- The page freezes

| Browser Affected | Version |
|---|---|
|Chrome|x|
</details>

**Comment by dsuren1** [comment] 2021-05-24 13:53
This issue should be fixed after this [PR ](https://github.com/geosolutions-it/MapStore2/pull/6891)is merged

**Comment by allyoucanmap** [comment] 2021-05-24 14:04
@dsuren1 could you please describe what was causing the issue in the style editor?

**Comment by dsuren1** [comment] 2021-05-24 14:10
@allyoucanmap 
Happens with the Select field (ex. fonts) with multi selectable option where [useeffect ](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/styleeditor/Fields.jsx#L228)check for the isEqual which is always true as soon as value is selected.

**Comment by tdipisa** [comment] 2021-05-25 08:53
@ElenaGallo the PR https://github.com/geosolutions-it/MapStore2/issues/6891 should fix also this issue. Please proceed with the test. as soon as the updates provided are deployed in DEV.

**Closed** 2021-05-25 10:20 UTC
Labels: Accepted, C183-ALMAVIVA-2020-GeoNode-DEV, Priority: Blocker, StyleEditor, bug

**Comment by allyoucanmap** [comment] 2021-06-07 12:22
just did some additional tests with different styles and the text symbolizer was freezing the application.
I opened a new issue because the steps to reproduce are different:

https://github.com/geosolutions-it/MapStore2/issues/6951
