### ISSUE TITLE
Strange error from http-proxy

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7862] opened 2022-02-14 09:04 UTC
## Description

Strange HTTP 400 response when passing through the http-proxy from v1.2-SNAPSHOT. Sample of request is:

https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/8e5cfd6e-77a2-4698-9095-bf36aea2a2f6)

Using the [latest stable version of MS](https://mapstore.geosolutionsgroup.com/mapstore/#/) where v1.1.1 of the http-proxy is used (see [here](https://github.com/geosolutions-it/MapStore2/blob/2021.02.xx/java/web/pom.xml#L37)) the problem doesn't occur:

https://qa-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities

## How to reproduce

-  Open a map and add the following WMS source to the Catalog tool: http://georchestra.geo-solutions.it/geoserver/wms

*Expected Result*

It is possible to load the WMS Capabilities.

*Current Result*

A HTTP 400 error is returned

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Probably connected to https://github.com/geosolutions-it/http-proxy/issues/59

**Comment by nmco** [comment] 2022-02-14 14:09
@tdipisa this issue has no client label and is open in the MapStore repository, we are going o have a look but the contextualization needs to be better.

In which context should this be invoiced? Why is the issue open in MapStore?

**Comment by tdipisa** [comment] 2022-02-14 14:56
@nmco this is caused to the http-proxy updates provided for c027.

**Comment by ydeliorman** [comment] 2022-02-14 15:01
@nmco 
While looking for a solution to this problem, I have found a minor bug which is wms request link missing required parameters. 

Missing WMS Request Link Problem:
We are assigning WMS getCapabilities request url variable in [here](https://github.com/geosolutions-it/http-proxy/blob/421509c200b229dd23f4c36fedcf7bc70489b90d/src/main/java/it/geosolutions/httpproxy/HTTPProxy.java#L284) is like this below:
`https://georchestra.geo-solutions.it/geoserver/wms?service=WMS`.  The problem is we are missing the remaining parameters of the request.

It does not have request and version parameters like 
`https://georchestra.geo-solutions.it/geoserver/wms?service=WMS&request=GetCapabilities&version=1.3.0`

Plan for fixing getCapabilities URL:
We build the url from the [set](https://github.com/geosolutions-it/http-proxy/blob/421509c200b229dd23f4c36fedcf7bc70489b90d/src/main/java/it/geosolutions/httpproxy/HTTPProxy.java#L272) during the iteration.

Bad hostport: 
I investigated this but could not find a solution yet. Will continue to investigate tomorrow.

**Comment by nmco** [comment] 2022-02-15 12:30
@shadab-geo can you quickly review @ydeliorman?

**Comment by ydeliorman** [comment] 2022-02-22 12:30
The problem is related to TLS. When we send the request by adding the 443 port number, the functionality is working. We will be investigating with @taba90  why such a behavior is happening. The quick fix is just to put 443 port number when we are having the https request but will investigate more.

Resource about TLS is [here](https://docs.apigee.com/api-platform/troubleshoot/runtime/400-bad-request-plain-http-request-sent-to-https-port). 

`https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it:443%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities`

**Comment by ydeliorman** [comment] 2022-02-23 13:47
@nmco @tdipisa 
The problem is with the upgraded apache library. The previous version is set to default port 433 for https request. However, the upgraded version is setting default port to -1. I will be writing a quick fix for this and test for both HTTP and HTTPS. The PR should be ready tomorrow morning in IT time.

**Comment by taba90** [comment] 2022-02-23 13:54
@tdipisa the same issue is affecting also the problem that the client encountered with the example url you in the mail for port 80.
The fix that Yalin will provide should fix both issues.

**Comment by tdipisa** [comment] 2022-02-23 13:56
> @tdipisa the same issue is affecting also the problem that the client encountered with the example url you in the mail for port 80. The fix that Yalin will provide should fix both issues.

I was imaging @taba90. Thank you for the confirmation.

**Comment by ydeliorman** [comment] 2022-02-24 07:35
@taba90 PR is ready to be reviewed
https://github.com/geosolutions-it/http-proxy/pull/63

**Comment by ydeliorman** [comment] 2022-02-24 12:15
@tdipisa fix is merged to the main. Could you do the checks, please?

**Comment by tdipisa** [comment] 2022-02-24 13:44
Hi @ydeliorman I will check this as soon as possible. I'm not sure I will be able to to it by this week, maybe on monday. I will let you know asap.

**Comment by tdipisa** [comment] 2022-03-01 16:48
@ydeliorman I've tested this. Please see my comment [here](https://github.com/geosolutions-it/MapStore2-C027/issues/87#issuecomment-1055641602).

**Comment by tdipisa** [comment] 2022-03-07 14:04
Tested in c027 client environment with both 1.3-SNAPSHOT and 1.2-SNAPSHOT It is working now.

**Comment by tdipisa** [comment] 2022-03-07 14:05
@ElenaGallo please to a test in MS DEV as soon as #7349 is closed.

**Closed** 2022-03-15 15:42 UTC
Labels: bug, investigation, Priority: Blocker, Accepted, Internal, C027-COMUNE_FI-2021-SUPPORT
